"""Centralized application configuration and path resolution.

The deployment service reads configuration from environment variables while
deriving stable filesystem paths from the project root. Keeping path and service
settings in one class prevents model loading, storage, database, and Kafka code
from duplicating environment parsing logic.
"""

import os
from urllib.parse import quote_plus
from pathlib import Path


class AppConfig:
    """Environment-backed settings for API, inference, storage, and integrations.

    The class is intentionally static because the service reads configuration at
    import/startup time and shares those values across model loading, request
    handling, persistence, Kafka, MLflow, and Hugging Face integration code.
    Keeping the settings here makes deployment differences explicit while
    preserving stable paths for local development.
    """

    # Base paths are derived instead of hard-coded so the app works from local
    # Python runs, Docker containers, and CI without changing source code.
    ROOT_DIR = Path(__file__).resolve().parent.parent.parent

    # Top-level project directories. These form the shared contract between the
    # API, static frontend, generated prediction artifacts, and model artifacts.
    APP_DIR = ROOT_DIR / "app"
    ASSETS_DIR = ROOT_DIR / "assets"
    FRONTEND_DIR = ROOT_DIR / "frontend"
    MODELS_ROOT = ROOT_DIR / "saved_models"

    # Model categories mirror the release layout generated by the MLOps layer.
    # Keeping this structure explicit makes missing or misplaced artifacts easy
    # to diagnose during startup checks.
    CLASSIFICATION_DIR = MODELS_ROOT / "healthy_unhealthy"
    DISEASES_DIR = MODELS_ROOT / "diseases"
    SEGMENTATION_DIR = MODELS_ROOT / "segmentation"

    # Binary healthy/unhealthy ensemble members. Each directory is expected to
    # contain metadata plus the runtime artifact selected by MODEL_RUNTIME.
    DENSENET_PATH = CLASSIFICATION_DIR / "densenet"
    EFFICIENTNET_PATH = CLASSIFICATION_DIR / "efficientnet"
    INCEPTION_PATH = CLASSIFICATION_DIR / "inception"
    MOBILENET_PATH = CLASSIFICATION_DIR / "mobilenet"

    # Disease subtyping currently uses one DenseNet model behind the binary
    # ensemble gate, so the runtime only needs this single diseases directory.
    DISEASE_DENSENET_PATH = DISEASES_DIR / "densenet"

    # Segmentation produces both the visible mask artifact and the lung ROI used
    # by disease classification.
    UNET_PATH = SEGMENTATION_DIR / "unet_xception"

    # Mapping and artifact paths are part of the API contract: labels and image
    # links returned to clients should remain stable across runtime backends.
    CLASSIFICATION_JSON = ASSETS_DIR / "healthy_unhealthy_mapping.json"
    DISEASES_JSON = ASSETS_DIR / "diseases_mapping.json"
    PREDICTION_DIR = ASSETS_DIR / "predictions"
    PREDICTION_STORAGE_BACKEND = os.getenv("PREDICTION_STORAGE_BACKEND", "local").lower()
    PREDICTION_PUBLIC_BASE_URL = os.getenv(
        "PREDICTION_PUBLIC_BASE_URL",
        "/static/predictions",
    ).rstrip("/")
    SUPABASE_URL = os.getenv("SUPABASE_URL", "").rstrip("/")
    SUPABASE_SERVICE_ROLE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY", "")
    SUPABASE_STORAGE_BUCKET = os.getenv(
        "SUPABASE_STORAGE_BUCKET",
        "lung-detection-predictions",
    )
    SUPABASE_SIGNED_URL_EXPIRES_SECONDS = int(
        os.getenv("SUPABASE_SIGNED_URL_EXPIRES_SECONDS", "3600")
    )

    # Global inference and integration settings. Environment variables let the
    # same source tree run as a local app, Docker Compose stack, or cloud service.
    IMAGE_SIZE = (256, 256)
    MODEL_RUNTIME = os.getenv("MODEL_RUNTIME", "onnx").lower()
    CORS_ALLOW_ORIGINS = [
        origin.strip()
        for origin in os.getenv("CORS_ALLOW_ORIGINS", "").split(",")
        if origin.strip()
    ]
    DB_HOST = os.getenv("DB_HOST", "localhost")
    DB_PORT = os.getenv("DB_PORT", "1433")
    DB_NAME = os.getenv("DB_NAME", "lung_detection")
    DB_USER = os.getenv("DB_USER", "sa")
    DB_PASSWORD = os.getenv("DB_PASSWORD", "")
    DB_DRIVER = os.getenv("DB_DRIVER", "ODBC Driver 18 for SQL Server")
    DB_ENCRYPT = os.getenv("DB_ENCRYPT", "yes")
    DB_TRUST_SERVER_CERTIFICATE = os.getenv("DB_TRUST_SERVER_CERTIFICATE", "yes")
    DB_ECHO = os.getenv("DB_ECHO", "false").lower() == "true"
    DB_LOGGING_ENABLED = os.getenv("DB_LOGGING_ENABLED", "true").lower() == "true"
    # Database backend: "mssql" (default, local full stack) or "postgres" (cloud deploy).
    DB_BACKEND = os.getenv("DB_BACKEND", "mssql").lower()
    # Full SQLAlchemy URL. When set it takes precedence over the discrete DB_* vars.
    # Render/Railway inject this automatically for their managed Postgres.
    DATABASE_URL = os.getenv("DATABASE_URL", "")
    # Optional Postgres TLS mode (managed Postgres usually needs "require").
    DB_SSLMODE = os.getenv("DB_SSLMODE", "")
    LOGS_API_KEY = os.getenv("LOGS_API_KEY", "")
    KAFKA_ENABLED = os.getenv("KAFKA_ENABLED", "true").lower() == "true"
    KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "127.0.0.1:9092")
    KAFKA_TOPIC_PREDICTIONS = os.getenv("KAFKA_TOPIC_PREDICTIONS", "lung.predictions")
    KAFKA_CLIENT_ID = os.getenv("KAFKA_CLIENT_ID", "lung-api-producer")
    KAFKA_SECURITY_PROTOCOL = os.getenv("KAFKA_SECURITY_PROTOCOL", "PLAINTEXT")
    KAFKA_SASL_MECHANISM = os.getenv("KAFKA_SASL_MECHANISM", "")
    KAFKA_SASL_USERNAME = os.getenv("KAFKA_SASL_USERNAME", "")
    KAFKA_SASL_PASSWORD = os.getenv("KAFKA_SASL_PASSWORD", "")
    KAFKA_GROUP_DB = os.getenv("KAFKA_GROUP_DB", "lung-consumer-db")
    KAFKA_GROUP_MONITORING = os.getenv("KAFKA_GROUP_MONITORING", "lung-consumer-monitoring")
    KAFKA_GROUP_ANALYTICS = os.getenv("KAFKA_GROUP_ANALYTICS", "lung-consumer-analytics")
    KAFKA_GROUP_DOCTOR = os.getenv("KAFKA_GROUP_DOCTOR", "lung-consumer-doctor")
    KAFKA_GROUP_NOTIFICATIONS = os.getenv("KAFKA_GROUP_NOTIFICATIONS", "lung-consumer-notifications")

    MLFLOW_ENABLED = os.getenv("MLFLOW_ENABLED", "false").lower() == "true"
    MLFLOW_STRICT = os.getenv("MLFLOW_STRICT", "false").lower() == "true"
    MLFLOW_TRACKING_URI = os.getenv("MLFLOW_TRACKING_URI", "http://localhost:5000")
    MLFLOW_MODEL_STAGE = os.getenv("MLFLOW_MODEL_STAGE", "Production")

    MLFLOW_MODEL_NAME_DENSENET_BINARY = os.getenv("MLFLOW_MODEL_NAME_DENSENET_BINARY", "lung-binary-densenet")
    MLFLOW_MODEL_NAME_EFFICIENTNET_BINARY = os.getenv("MLFLOW_MODEL_NAME_EFFICIENTNET_BINARY", "lung-binary-efficientnet")
    MLFLOW_MODEL_NAME_INCEPTION_BINARY = os.getenv("MLFLOW_MODEL_NAME_INCEPTION_BINARY", "lung-binary-inception")
    MLFLOW_MODEL_NAME_MOBILENET_BINARY = os.getenv("MLFLOW_MODEL_NAME_MOBILENET_BINARY", "lung-binary-mobilenet")
    MLFLOW_MODEL_NAME_DISEASES = os.getenv("MLFLOW_MODEL_NAME_DISEASES", "lung-diseases-densenet")
    MLFLOW_MODEL_NAME_SEGMENTATION = os.getenv("MLFLOW_MODEL_NAME_SEGMENTATION", "lung-segmentation-unet-xception")

    HF_MODEL_DOWNLOAD_ENABLED = os.getenv("HF_MODEL_DOWNLOAD_ENABLED", "false").lower() == "true"
    HF_MODEL_REPO_ID = os.getenv("HF_MODEL_REPO_ID", "a1mohamadd/lung-disease-detection")
    HF_MODEL_REPO_TYPE = os.getenv("HF_MODEL_REPO_TYPE", "model")
    HF_MODEL_REVISION = os.getenv("HF_MODEL_REVISION", "main")
    HF_MODEL_REPO_SUBDIR = os.getenv("HF_MODEL_REPO_SUBDIR", "").strip("/")
    HF_TOKEN = os.getenv("HF_TOKEN") or os.getenv("HUGGINGFACE_HUB_TOKEN", "")

    @staticmethod
    def get_metadata_path(model_dir: Path) -> Path:
        """Return the metadata file path for a model artifact directory.

        Args:
            model_dir: Directory containing a model runtime artifact and its
                ``metadata.yaml`` contract.

        Returns:
            Path to the metadata file expected by startup and model loaders.
        """
        return model_dir / "metadata.yaml"

    @staticmethod
    def get_database_url() -> str:
        """Resolve the SQLAlchemy database URL for the configured backend.

        Explicit ``DATABASE_URL`` values win because managed cloud databases
        usually inject a complete connection string. When it is absent, the URL
        is assembled from discrete ``DB_*`` variables for local Compose stacks.

        Returns:
            SQLAlchemy-compatible database URL.
        """
        # Explicit full URL wins (12-factor; Render/Railway inject DATABASE_URL).
        if AppConfig.DATABASE_URL:
            return AppConfig._normalize_database_url(AppConfig.DATABASE_URL)

        # Discrete vars are useful for Docker Compose and local development.
        if AppConfig.DB_BACKEND == "postgres":
            return AppConfig._build_postgres_url()

        # Default: SQL Server, preserving the original local full-stack setup.
        return AppConfig._build_mssql_url()

    @staticmethod
    def _normalize_database_url(url: str) -> str:
        """Normalize provider Postgres URLs to the psycopg2 SQLAlchemy dialect.

        Args:
            url: Raw database URL supplied by the environment.

        Returns:
            URL with an explicit SQLAlchemy driver when the provider uses a bare
            Postgres scheme.
        """
        # Normalize the bare schemes some providers emit so SQLAlchemy uses psycopg2.
        if url.startswith("postgres://"):
            return "postgresql+psycopg2://" + url[len("postgres://"):]
        if url.startswith("postgresql://"):
            return "postgresql+psycopg2://" + url[len("postgresql://"):]
        return url

    @staticmethod
    def _build_postgres_url() -> str:
        """Build a Postgres SQLAlchemy URL from discrete environment variables.

        Returns:
            SQLAlchemy URL using ``postgresql+psycopg2`` and optional SSL mode.
        """
        user = quote_plus(AppConfig.DB_USER)
        password = quote_plus(AppConfig.DB_PASSWORD)
        host = AppConfig.DB_HOST
        port = AppConfig.DB_PORT.strip() if AppConfig.DB_PORT else ""
        # Fall back to the Postgres default port when unset or left at the MSSQL default.
        if port in ("", "1433"):
            port = "5432"

        url = f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{AppConfig.DB_NAME}"
        if AppConfig.DB_SSLMODE:
            url += f"?sslmode={AppConfig.DB_SSLMODE}"
        return url

    @staticmethod
    def _build_mssql_url() -> str:
        """Build a SQL Server SQLAlchemy URL from discrete environment variables.

        Returns:
            SQLAlchemy URL using ``mssql+pyodbc`` with encryption and trust
            options carried through to the ODBC driver.
        """
        user = quote_plus(AppConfig.DB_USER)
        password = quote_plus(AppConfig.DB_PASSWORD)
        driver = quote_plus(AppConfig.DB_DRIVER)
        host = AppConfig.DB_HOST
        port = AppConfig.DB_PORT.strip() if AppConfig.DB_PORT else ""

        server = host
        if port and "\\" not in host:
            server = f"{host}:{port}"

        return (
            f"mssql+pyodbc://{user}:{password}@{server}/{AppConfig.DB_NAME}"
            f"?driver={driver}"
            f"&Encrypt={AppConfig.DB_ENCRYPT}"
            f"&TrustServerCertificate={AppConfig.DB_TRUST_SERVER_CERTIFICATE}"
        )
