# Binary Healthy-Unhealthy Lung Classification: EfficientNetV2B3 4-Channel Mask Attention

<div style="text-align: center;">
    <img src="../images/med_ai.jpg" alt="Medical AI" style="display: block; margin: 0 auto;">
</div>

---

This notebook implements an advanced diagnostic pipeline for binary lung health classification (Healthy vs. Unhealthy). By utilizing an **EfficientNetV2B3** backbone modified to accept a **4-channel input**, the model learns to treat the anatomical lung mask as a dedicated spatial attention mechanism.

For more inforamtion you can check the Keras official Documentation about the EfficientNetV2 models: [EfficientNetV2 Keras Documentation](https://keras.io/api/applications/efficientnet_v2/)  
Also can Check EfficientNetV2B3 TensorFlow official Documentation here: [EfficientNetV2B3 Tensorflow Documentation](https://www.tensorflow.org/api_docs/python/tf/keras/applications/EfficientNetV2B3)

## 🧬 1. Specialized Data Engineering & Manual Preprocessing
The data pipeline is designed to handle high-resolution imagery while ensuring the mask and image remain spatially synchronized:
* **Binary Remapping:** Labels are remapped such that class `1` (Normal) is converted to `0` and other classes are treated as `1` (Unhealthy).
* **Manual Preprocessing (No Defaults):** The standard EfficientNet `preprocess_input` is bypassed. Images are manually scaled to the `[-1.0, 1.0]` range using the formula `(image / 127.5) - 1.0`. 
* **4-Channel Integration:** The preprocessed RGB image is concatenated with the binary mask to form a single `(256, 256, 4)` tensor.
* **Synchronized Augmentation:** Geometric transformations (Rotation, Zoom, Horizontal Flip) are applied to the entire 4-channel stack simultaneously. This ensures the mask always aligns perfectly with the lung tissue, even after distortion.

## 🏗️ 2. Architectural Model Surgery: The 4th Channel
Since pre-trained EfficientNet models only support 3-channel (RGB) inputs, this notebook performs "surgery" on the model's initial layer to allow for a 4th mask channel without losing pre-trained knowledge:
* **Kernel Extraction:** The notebook first loads a standard 3-channel EfficientNetV2B3 and extracts the weights from the first convolutional layer (`input_conv`).
* **Weight Initialization for Mask:** To give the 4th channel a stable starting point, the new weights are created by **averaging the weights of the original three RGB channels**. This ensures the model treats the mask intensity with a similar scale as the original image features.
* **Layer Injection:** A new 4-channel "blank" backbone is created. The surgically modified kernel (now 4 channels deep) is injected into the first layer, while the remaining pre-trained weights for all other layers are copied over exactly from the 3-channel model.
* **Mask as Learned Attention:** By feeding the mask as a 4th channel, the network learns a mathematical relationship where the features located within the masked "lung zone" are prioritized for classification, effectively ignoring background noise.

## 🚀 3. Multi-Phase Progressive Training
To adapt the pre-trained weights to the new 4th channel safely, a three-stage fine-tuning strategy is employed:
1.  **Warm-Up Phase (Epochs 1-10):** The entire backbone is frozen. Only the custom classification head (Dense layers of 512 and 64 units) is trained at a learning rate of `3e-4`.
2.  **Mid-Tune Phase (Epochs 10-30):** Select backbone layers are unfrozen to allow the model to begin adapting its internal features to the 4-channel input at a reduced learning rate of `1e-5`.
3.  **Full Fine-Tuning (Epochs 30-130):** The entire backbone is unfrozen for deep optimization, aiming for maximum clinical sensitivity.

## 📊 4. Clinical Performance & Validation
Training success is measured using medical-grade metrics:
* **Primary Metrics:** Accuracy, AUC, Precision, and Recall.
* **Clinical Goal:** High **Recall** is prioritized to ensure the model acts as an effective screening tool, minimizing the risk of missing unhealthy cases.
* **Checkpointing:** The `ModelCheckpoint` callback is used to save the version of the model that achieves the lowest **Validation Loss**, ensuring the final production model has the best generalization capability.

## Section 1: Environment Setup and Distribution Strategy

This initial section focuses on configuring the notebook's execution environment for the classification fine-tuning task. It imports all necessary deep learning and utility libraries, enforces deterministic behavior for reproducibility, and establishes the optimal hardware distribution strategy (TPU, GPU, or CPU) required for the efficient training of the large EfficeintNet model.

---

### 1.1 Library Imports and Version Check

This subsection imports the comprehensive set of tools required for building, training, and managing the EfficientNet classification model.

* **Core ML Frameworks & Utilities:** Imports `tensorflow` (`tf`), `json`, `numpy` (`np`), `math`, and `os` and `matplotlib`.
* **Model Components:** Imports the `EfficientNetV2B3` model, `tensorflow.keras.layers` (`tfl`).
* **Metrics and Callbacks:** Imports specific metrics (`metrics`) and all necessary callbacks (`ModelCheckpoint`, `EarlyStopping`, `ReduceLROnPlateau`, `TensorBoard`) to manage the multi-step fine-tuning process.
* **Version Check:** The TensorFlow version is explicitly printed to confirm compatibility.

In [5]:
# Import neccesary libraries
import tensorflow as tf
import numpy as np
import json
import random
import os
import math
import matplotlib.pyplot as plt
import tensorflow.keras.layers as tfl
from tensorflow.keras import metrics
from tensorflow.keras.applications import EfficientNetV2B3
from tensorflow.keras.applications.efficientnet_v2 import preprocess_input
from tensorflow.keras.callbacks import ModelCheckpoint, ReduceLROnPlateau, EarlyStopping, TensorBoard

In [2]:
print(tf.__version__)

2.20.0


---
### 1.2 Reproducibility and Utility Functions

This subsection defines helper functions to ensure the training run is deterministic and to initialize the environment's state, particularly for distributed training.

#### 1.2.1 `seed_everthing` Function
This function sets the random seeds across all major components (`tf`, `np`, `random`) to a fixed value (defaulting to 28). This is a best practice to ensure that model weight initialization, data shuffling, and other stochastic processes are identical across runs, making experiments reproducible.

In [3]:
def seed_everthing(SEED= 28):
    """
    Sets the global random seeds for reproducibility across TensorFlow, NumPy, and Python's random module.
    
    Args:
        SEED (int): The integer seed value to be used.
    """
    # Set the seed for TensorFlow operations (both CPU and GPU)
    tf.random.set_seed(SEED)
    # Set the seed for NumPy's random number generator
    np.random.seed(SEED)
    # Set the seed for Python's built-in random module
    random.seed(SEED)

seed_everthing()

#### 1.2.2 `get_strategy` Function and Distribution Strategy Activation
This function automatically detects the best available hardware accelerator and configures the corresponding TensorFlow Distribution Strategy for parallel computation. 

* **TPU Priority:** It first attempts to initialize and connect to a TPU using `TPUClusterResolver` and `tf.distribute.TPUStrategy`.
* **GPU Fallback:** If a TPU is not found, it checks for available GPUs and uses `tf.distribute.MirroredStrategy`, which is optimal for multi-GPU training.
* **CPU Default:** If neither TPU nor GPU is available, it defaults to the standard strategy.
* **Activation:** The function is called, and the resulting `strategy` object is stored. The number of active replicas (cores/GPUs) is printed, confirming the multi-device setup for training.

In [4]:
def get_strategy():
    """
    Detects and returns the best TensorFlow distribution strategy.
    - TPUStrategy for TPU(s)
    - MirroredStrategy for GPU(s)
    - Default strategy for CPU
    """
    try:
        # Try TPU first
        tpu = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='local')
        tf.config.experimental_connect_to_cluster(tpu)
        tf.tpu.experimental.initialize_tpu_system(tpu)
        strategy = tf.distribute.TPUStrategy(tpu)
        print("Using TPU strategy:", type(strategy).__name__)
    except Exception:
        # If TPU not available, try GPU
        gpus = tf.config.list_physical_devices('GPU')
        if gpus:
            strategy = tf.distribute.MirroredStrategy()
            print("Using GPU strategy:", type(strategy).__name__)
        else:
            # Fallback CPU
            strategy = tf.distribute.get_strategy()
            print("No TPU/GPU found. Using CPU strategy:", type(strategy).__name__)

    print("REPLICAS:", strategy.num_replicas_in_sync)
    return strategy

#### 1.2.3 `GPU Memory` Management

This subsection implements a necessary pre-initialization fix for GPU environments: enabling **dynamic memory growth**. By default, TensorFlow allocates nearly all GPU memory upfront. Setting memory growth ensures that memory is only allocated as needed during runtime, preventing premature out-of-memory (OOM) errors and allowing shared use of the GPU resource. This must be executed before any GPU-based operation or strategy is initialized. 

In [5]:
# --- ADD THIS FIX AT THE TOP OF YOUR SCRIPT ---
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    try:
        # Set memory growth to be enabled for all GPUs
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        print(f"Enabled memory growth for {len(gpus)} GPU(s)")
    except RuntimeError as e:
        # Memory growth must be set before GPUs have been initialized
        print(e)
# --- END OF FIX ---

Enabled memory growth for 1 GPU(s)


In [6]:
# Call it
strategy = get_strategy()

INFO:tensorflow:Deallocate tpu buffers before initializing tpu system.
INFO:tensorflow:Initializing the TPU system: local
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
Using GPU strategy: MirroredStrategy
REPLICAS: 1


I0000 00:00:1764783049.018727     474 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 2248 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1650, pci bus id: 0000:01:00.0, compute capability: 7.5


---
### 1.3 Hyperparameter and Global Constant Configuration

This subsection defines the critical hyperparameters and global constants that govern the data pipeline setup and the multi-step fine-tuning process. The learning rates and epoch boundaries are essential for managing the four phases of training: Warmup, Mid-Tune, Unfreeze for Fine-Tune Whole Model.

| Constant | Value | Description |
| :--- | :--- | :--- |
| **`AUTO`** | `tf.data.AUTOTUNE` | Used for dynamic optimization of CPU threads in the data input pipeline. |
| **`DATA_DIR`** | `'./data/tfrecords/'` | Local path to the directory containing training and validation TFRecord files. |
| **`MODELS_DIR`** | `'./models/'` | Local directory path for saving trained model checkpoints. |
| **`IMAGE_SIZE`** | `(256, 256)` | The target spatial dimension for image resizing. |
| **`MASK_SIZE`** | `IMAGE_SIZE` | The target spatial dimension for mask resizing, matching the image size. |
| **`SHUFFLE_SIZE`** | `1024` | The buffer size used for shuffling the dataset, balancing randomness with memory usage. |
| **`NUM_CLASSES`** | `2` | The number of output classes: **Healthy** (0) and **Unhealthy** (1). |
| **`BATCH_SIZE_PER_REPLICA`** | `8` | The batch size processed by each individual TPU core or GPU. |
| **`GLOBAL_BATCH_SIZE`** | Calculated | The total effective batch size across all available hardware replicas. |
| **`WARMUP_LR`** | `3e-4` | Learning rate for the initial **Warmup** phase (Epochs 0 to 10). |
| **`BACKBONE_WARMUP_LR`** | `1e-5` | Learning rate for the **Mid-Tune** phase (Epochs 10 to 30). |
| **`FINE_TUNE_LR`** | `1e-6` | Learning rate for the **Fine-Tune Whole Model** phase (Epochs 30 to 130). |
| **`INITIAL_EPOCH`** | `10` | Epoch boundary marking the end of the **Warmup** phase. |
| **`MIDTUNE_EPOCH`** | `30` | Epoch boundary marking the end of the **Mid-Tune** phase. |
| **`UNFREEZE_EPOCH`** | `130` | Epoch boundary marking the end of the **Fine-Tune Whole Model** phase. |

The output confirms the effective batch size for distributed training:
> `Global Batch size: [Calculated Value]`

In [7]:
AUTO = tf.data.AUTOTUNE
DATA_DIR = '../data/tfrecords/'
MODELS_DIR = '../models/'
IMAGE_SIZE = (256, 256)
MASK_SIZE = IMAGE_SIZE
SHUFFLE_SIZE = 1024
WARMUP_LR = 3e-4
BACKBONE_WARMUP_LR = 1e-5
FINE_TUNE_LR = 1e-6
INITIAL_EPOCH = 10
MIDTUNE_EPOCH = INITIAL_EPOCH + 20
UNFREEZE_EPOCH = MIDTUNE_EPOCH + 100
NUM_CLASSES = 2
BATCH_SIZE_PER_REPLICA = 8
GLOBAL_BATCH_SIZE = BATCH_SIZE_PER_REPLICA * strategy.num_replicas_in_sync
print(f'Global Batch size: {GLOBAL_BATCH_SIZE}')

Global Batch size: 8


---
### 1.5 Model Checkpoint Paths

This subsection defines the specific file paths where the model weights will be saved after each phase of the multi-step fine-tuning process. This ensures that the model can be consistently loaded at the beginning of the next training phase (Warmup, Mid-Tune, Fine-Tune) or recovered after a crash.

| Path Variable | Purpose | Phase Completed |
| :--- | :--- | :--- |
| `warmup_efficientnet_path` | Saves the model after the initial **Warmup** phase. | Epoch 10 |
| `midtune_efficentnet_path` | Saves the model after the **Mid-Tune** phase. | Epoch 30 |
| `final_efficientnet_path` | Saves the model after the long **Fine-Tune Whole Model** phase. | Epoch 130 |

In [8]:
warmup_efficientnet_path = os.path.join(MODELS_DIR, 'classification/initial_efficientnetb3_healthy_model.keras')
midtune_efficientnet_path = os.path.join(MODELS_DIR, 'classification/midtune_efficientnetb3_healthy_model.keras')
final_efficientnet_path = os.path.join(MODELS_DIR, 'classification/final_efficientnetb3_healthy_model.keras')

### 1.6 Class Mapping

This crucial subsection handles the mapping of the original disease classes into the final binary classes to get familiar with trasnformation of classes from source to binary detection.

#### 1.6.1 Loading Class-to-Index Mappings
The original four disease classes (e.g., COVID, Normal) and the newly defined binary classes (Healthy, Unhealthy) are loaded from JSON files.

* `class_mapping`: The original mapping from class name to its integer index (0, 1, 2, 3).
* `healty_binary_mapping`: The final mapping used for the classification head: **Healthy (0)** and **Unhealthy (1)**. 

In [6]:
# Loading original class mapping
class_mapping_path = '../data/class_mapping.json'
with open (class_mapping_path, 'r') as f:
    class_mapping = json.load(f)

print(class_mapping)

{'COVID': 0, 'Normal': 1, 'Viral Pneumonia': 2, 'Lung_Opacity': 3}


In [7]:
# Loading Binary class mapping
healthy_binary_mapping_path = '../data/healthy_binary_mapping.json'
with open(healthy_binary_mapping_path, 'r') as f:
    healty_binary_mapping = json.load(f)

print(healty_binary_mapping)

{'Healthy': 0, 'Unhealthy': 1}


---
## Section 2: Data Preprocessing and Augmentation Pipeline

This section defines the core components of the data input pipeline, focusing on robust preprocessing and synchronized augmentation necessary for feeding masked X-ray images into the EfficeintNetV2 model. This pipeline is crucial for converting raw TFRecord data into properly scaled, augmented, and masked tensors ready for training.

---

### 2.1 Data Parsing and Label Remapping

This subsection contains the initial functions for handling raw TFRecord data.

#### 2.1.1 `parse_base_function`
This function is responsible for deserializing a single TFRecord example. It decodes the raw PNG byte strings for the image and the mask, resizes them to the global `IMAGE_SIZE` and `MASK_SIZE` (using bilinear for image and nearest neighbor for mask), and casts them to the appropriate `float32` and `int32` types. The mask is normalized to a binary `[0, 1]` float tensor.

In [9]:
def parse_base_function(example):
    '''
    Parses a single TFRecord example, decoding and resizing the image and mask.

    Returns:
        tuple: (img, mask, label) tensors after initial decoding and resizing.
    '''
    # Define the dictionary of features expected in the TFRecord
    feature_description = {
        'image': tf.io.FixedLenFeature([], tf.string),
        'mask': tf.io.FixedLenFeature([], tf.string),
        'class': tf.io.FixedLenFeature([], tf.int64)
    }

    # Parse the input record
    example = tf.io.parse_single_example(example, feature_description)
    
    # Decode image and mask
    img = tf.io.decode_png(example['image'], channels= 3)
    mask = tf.io.decode_png(example['mask'], channels= 1)

    # Resize image using bilinear interpolation for quality
    img = tf.image.resize(img, IMAGE_SIZE, method= 'bilinear')
    img = tf.cast(img, tf.float32)

    # Resize mask using nearest neighbor to preserve boundaries
    mask = tf.image.resize(mask, MASK_SIZE, method= 'nearest')
    # Normalize and ensure binarization (0.0 or 1.0)
    mask = tf.cast(mask, tf.float32) / 255.0
    mask = tf.round(mask)

    # Return label also
    label = tf.cast(example['class'], tf.int32)

    return img, mask, label

#### 2.1.2 `remap_for_binary`
This function performs the final conversion of the class index into the binary label required for the classification task. It maps the original `Normal` class (index 1) to the binary class **0 (Healthy)**, and all other original disease classes to the binary class **1 (Unhealthy)**.

In [10]:
def remap_for_binary(image, mask, label):
    '''
    Remaps the multiclass label (where 1 is one class, and others are combined) into a binary (0 or 1) float label.

    Args:
        image (tf.Tensor): Input image tensor.
        mask (tf.Tensor): Input mask tensor.
        label (tf.Tensor): Input integer label.

    Returns:
        tuple: (image, mask, new_label) where new_label is a binary float tensor.
    '''
    # Map original label 1 to 0, and all others to 1 (binary classification), because as we see in class mapping
    # Normal images has Label 1
    new_label = tf.where(tf.equal(label, 1), 0, 1)
    new_label = tf.cast(new_label, tf.float32)
    # Ensure label is in the correct shape for binary classification output (e.g., [1])
    new_label = tf.expand_dims(new_label, axis= -1)
    
    return image, mask, new_label

### 2.2 Augmentation Strategy

The augmentation strategy is implemented in a **sequential manner**, combining geometrical and color adjustments. 

#### 2.2.1 Geometrical Augmentation Layer
A Keras `Sequential` model (`geometric_aug`) is defined to apply synchronized geometrical transformations. Since the image (3 channels) and mask (1 channel) are concatenated for synchronization, the input has 4 channels. All transformations utilize `fill_mode='nearest'` to ensure that pixels introduced by rotation or zoom in the mask remain strictly binary (`0` or `1`).

* **RandomFlip('horizontal'):** Flips the image and mask horizontally.
* **RandomRotation(0.2):** Rotates the image and mask.
* **RandomZoom(0.1):** Applies a random zoom factor.

In [11]:
# Define the sequence of geometric augmentation layers for image + mask
geometric_aug = tf.keras.Sequential([
        # input_shape must include the mask channel (4 total)
        tfl.RandomFlip('horizontal', input_shape=(*IMAGE_SIZE, 4)),
        tfl.RandomRotation(0.2, interpolation='bilinear', fill_mode='nearest'),
        tfl.RandomZoom(0.1, interpolation='bilinear', fill_mode= 'nearest')
    ])

/home/a1mohamad/ai-env/lib/python3.12/site-packages/keras/src/layers/preprocessing/tf_data_layer.py:19: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


---
#### 2.2.2 `augment` Function
This function applies the full set of augmentations.

1.  **Synchronization:** Image and mask are concatenated, and the `geometric_aug` layer is applied to transform them simultaneously.
2.  **Splitting and Re-rounding:** The tensor is split back into image and mask. The mask is immediately **re-rounded** (`tf.round`) to ensure it remains a clean binary mask after interpolation from the geometrical transforms.
3.  **Color Augmentation:** Color adjustments `tf.image.random_contrast` and `tf.image.random_brightness` are then applied **only to the image**, ensuring the segmentation mask's integrity is preserved.then image clipped by 0.0 and 255.0 to prevents it from having larger and smaller values. also note that in color augmentation we focus to get more lights on images to the model can separate in perfectly comparing to **black background**.

In [12]:
def augment(image, mask, label):
    '''
    Applies both geometric (on image+mask) and color (on image only) augmentations to a batch of data.

    Args:
        image (tf.Tensor): Batch of image tensors.
        mask (tf.Tensor): Batch of mask tensors.
        label (tf.Tensor): Batch of label tensors.

    Returns:
        tuple: (image, mask, label) after augmentation.
    '''
    # Concatenate image (3 channels) and mask (1 channel) for synchronous geometric augmentation
    img_mask_concat = tf.concat([image, mask], axis=-1) # Shape [B, H, W, 4]
    # Apply the geometric augmentations
    img_mask_concat = geometric_aug(img_mask_concat, training=True)
    
    # Split them back
    image = img_mask_concat[..., :3]
    mask = img_mask_concat[..., 3:]
    mask = tf.round(mask) # Re-round mask after interpolation
    
    # Apply color augmentation (which doesn't affect mask)
    image = tf.image.random_contrast(image, 0.95, 1.2) # tf.image is safer here
    image = tf.image.random_brightness(image, 0.95, 1.2)
    # Clip to original values
    image = tf.clip_by_value(image, 0.0, 255.0)
    return image, mask, label

### 2.3 Final Preprocessing (`preprocess` function)

This function executes the final, critical data transformation and tensor assembly steps before data is passed to the **EfficientNetV2B3** model. It is specifically designed to support the **4-channel input strategy** by manually managing image normalization and mask concatenation, bypassing the model's internal preprocessing defaults.

#### EfficientNetV2 Complex Normalization vs. Manual Scaling

Standard **EfficientNetV2** models typically utilize a more complex normalization approach when `include_preprocessing=True`. While older architectures used simple rescaling, EfficientNetV2 often expects images to be normalized using **ImageNet mean and standard deviation**. This statistical normalization transforms the input $x$ into a standard normal distribution space for each color channel:

$$\text{Output}_c = \frac{x_c - \mu_c}{\sigma_c}$$

Where for ImageNet:
* $\mu = [0.485, 0.456, 0.406]$
* $\sigma = [0.229, 0.224, 0.225]$

#### Preprocessing Mechanism and 4-Channel Logic

In this notebook, we explicitly set `include_preprocessing=False` during model instantiation. This allows us to bypass the standard statistical normalization in favor of a manual **Inception-style rescaling**. This decision was made based on test-time evaluations confirming that manual normalization to the **$[-1, 1]$** range yields superior performance and more stable metrics on unseen test images compared to the complex statistical $\mu/\sigma$ approach.

The `preprocess` function implements this logic as follows:

1.  **Manual Image Rescaling:** The RGB image channels are rescaled from the raw $[0, 255]$ range to the normalized $[-1.0, 1.0]$ range using the industry-standard formula:
    $$\text{Output} = \frac{\text{Input}}{127.5} - 1$$
2.  **Mask Preservation (Zero Normalization):** It is critical to note that the **mask is not normalized**. Since the mask is already a binary tensor (values of $0.0$ or $1.0$), it is kept in its original form to act as a clear, high-contrast attention signal.
3.  **4-Channel Concatenation:** After the image is scaled, the RGB image and the single-channel mask are concatenated along the last axis. This creates a single tensor with a shape of `(256, 256, 4)`, combining the detailed texture of the lung (in the normalized space) with its anatomical boundary (in the binary space).

#### Clinical Significance of the $[-1.0, 1.0]$ Range

By manually forcing the image into the $[-1.0, 1.0]$ range while keeping the mask binary ($0.0/1.0$), we ensure:
* **Neutral Baseline:** The "average" pixel value is centered at $0.0$, which helps gradients propagate more efficiently during the fine-tuning phases.
* **Contrast with Mask:** The normalized lung tissue exists in a distinct mathematical space from the binary mask. This contrast helps the surgically modified first layer of the EfficientNetV2B3 backbone distinguish between the anatomical structure (the mask) and the pathological features (the image).
* **Test-Time Robustness:** This specific scaling was chosen because it demonstrated the best generalization on the test set, effectively mitigating noise and ensuring the model remains focused on the lung parenchyma defined by the 4th channel.

In [13]:
def preprocess(image, mask, label):
    '''
    Applies manual Inception-style scaling to the RGB image and concatenates the lung mask 
    to form a 4-channel input tensor. 
    
    This function replaces the standard EfficientNetV2 statistical normalization (ImageNet mean/std) 
    with a manual rescaling range that proved more robust during test-time evaluation.
    
    Args:
        image (tf.Tensor): Batch of RGB image tensors in the [0, 255] range.
        mask (tf.Tensor): Batch of binary mask tensors [0.0, 1.0].
        label (tf.Tensor): Batch of label tensors.
    
    Returns:
        tuple: (image_mask, label) where:
            - image_mask: A 4-channel tensor [R, G, B, Mask].
            - RGB channels are rescaled to the [-1.0, 1.0] range using: (image / 127.5) - 1.0
            - Mask channel remains binary [0.0, 1.0] to act as an attention signal.
    '''
    # normalize image manually(only image not mask)
    image = (image / 127.5) - 1.0
    # concat image and mask together
    image_mask = tf.concat([image, mask], axis=-1)
    
    return image_mask, label

## Section 3: Data Pipeline Creation and Configuration

This section brings together the preprocessing functions and global constants to construct the high-performance `tf.data.Dataset` pipelines for both training and validation. It ensures efficient data loading, optimal hardware utilization, and accurate calculation of training steps.

### 3.1 Training and Validation Split

The list of all TFRecord files is loaded from the specified directory (`DATA_DIR`). The data is split deterministically, reserving the final file for validation and using all preceding files for training. This ensures a consistent separation between the training and validation sets across runs.note that all tfrecords are randomly shuffled so distributions between train and val files are equal. 

* `train_files`: All TFRecord files except the last one.
* `val_files`: The last TFRecord file in the sorted list.

In [15]:
# Read all tfrecords files
all_files = sorted(tf.io.gfile.glob(os.path.join(DATA_DIR , '*.tfrecord')))
# Create train and val files
train_files = all_files[:-1]
val_files = all_files[-1:]

### 3.2 Optimized TF.Data Pipeline Function (`dataset`)

The `dataset` function constructs the final, optimized input pipeline using `tf.data` features to maximize throughput and utilize the hardware accelerator efficiently. 

The pipeline order is specifically designed for high performance in a distributed environment:

1.  **Parallel Reading and Non-Deterministic Order:** Reads multiple TFRecord files concurrently (`num_parallel_reads=AUTO`) and enables non-deterministic order (`ignore_order.experimental_deterministic = False`) to prevent bottlenecks and ensure maximal data throughput.
2.  **Per-Sample Mapping:** Applies `parse_base_function` and `remap_for_binary` to each individual record in parallel (`num_parallel_calls=AUTO`). These steps handle decoding, resizing, and binary label conversion.
3.  **Training Branch (Shuffle, Batch, Augment):**
    * **Shuffle:** Shuffles the raw samples before batching.
    * **Batch First:** Batches the data **before** augmentation (`dataset.batch`). This is crucial because it allows the `augment` function to run once per batch on the accelerator, processing many images in parallel (vectorization), which is far more efficient than augmenting one image at a time.
    * **Augmentation:** Applies the batch-level `augment` function (geometrical + color).
4.  **Pre-Batch Preprocessing:** The final `preprocess` function is applied just before prefetching.
5.  **Prefetching:** Uses `dataset.prefetch(AUTO)` to overlap the data preparation time (CPU/host) with the model execution time (TPU/GPU), ensuring the accelerator is never starved of data.

In [14]:
def dataset(tfrecords, batch_size= GLOBAL_BATCH_SIZE, shuffle_size= SHUFFLE_SIZE, is_training= True):
    '''
    Creates a robust and performant tf.data.Dataset pipeline.

    Args:
        tfrecords (list): List of TFRecord file paths.
        batch_size (int): The batch size to use.
        shuffle_size (int): The buffer size for shuffling.
        is_training (bool): Flag to enable/disable shuffling and augmentation.

    Returns:
        tf.data.Dataset: Configured dataset ready for training or validation.
    '''
    ignore_order = tf.data.Options()
    # Disable deterministic ordering for improved performance when reading files
    ignore_order.experimental_deterministic = False 
    
    # Load TFRecord files with parallel reading
    dataset = tf.data.TFRecordDataset(tfrecords, num_parallel_reads= AUTO)
    dataset = dataset.with_options(ignore_order)
    
    # Map decoding and label remapping functions
    dataset = dataset.map(parse_base_function, num_parallel_calls= AUTO)
    dataset = dataset.map(remap_for_binary, num_parallel_calls=AUTO)
    
    if is_training:
        dataset = dataset.shuffle(shuffle_size)
        # 1. Batch the data FIRST
        dataset = dataset.batch(batch_size, drop_remainder= True)
        # 2. Apply augmentation to the entire batch SECOND (efficient for Keras layers)
        dataset = dataset.map(augment, num_parallel_calls= AUTO)
    else:
        # For validation, just batch the data
        dataset = dataset.batch(batch_size, drop_remainder= True)

    # Apply the final preprocessing (scaling and masking)
    dataset = dataset.map(preprocess, num_parallel_calls= AUTO)

    # 3. Prefetch the augmented batches for optimal GPU utilization
    dataset = dataset.prefetch(AUTO)
    return dataset

In [16]:
# call function for creating train and val dataset
train_dataset = dataset(train_files, is_training= True)
val_dataset = dataset(val_files, is_training= False)

### 3.3 Dataset Instantiation and Size Calculation

This subsection instantiates the final `train_dataset` and `val_dataset` objects and calculates the essential metrics for the Keras `model.fit` call.
A helper function, `count_tfrecord`, is used to accurately count the total number of samples in the training and validation sets.

* `train_samples`: Total number of samples in the training set.
* `val_samples`: Total number of samples in the validation set.

The number of steps required per epoch is calculated based on the total number of samples and the `GLOBAL_BATCH_SIZE`, ensuring every sample is seen exactly once per epoch.

* `steps_per_epoch`: Calculated as $\lceil \frac{\text{train\_samples}}{\text{GLOBAL\_BATCH\_SIZE}} \rceil$
* `validation_steps`: Calculated as $\lceil \frac{\text{val\_samples}}{\text{GLOBAL\_BATCH\_SIZE}} \rceil$

The final calculated steps are printed to confirm the distributed training configuration.

In [17]:
def count_tfrecord(tfrecords):
    '''
    Counts the total number of examples across a list of TFRecord files.

    Args:
        tfrecords (list): List of TFRecord file paths.

    Returns:
        int: The total count of examples.
    '''
    count = 0
    for tfrecord in tfrecords:
        count += sum(1 for _ in tf.data.TFRecordDataset(tfrecord))
    return count

train_samples = count_tfrecord(train_files)
val_samples = count_tfrecord(val_files)
# Calculate steps based on sample counts and batch size
steps_per_epoch = math.ceil(train_samples / GLOBAL_BATCH_SIZE)
validation_steps = math.ceil(val_samples / GLOBAL_BATCH_SIZE)
print(f'Steps Per Epoch: {steps_per_epoch}\nValidation steps: {validation_steps}')

2025-12-03 21:01:34.233737: I tensorflow/core/kernels/data/tf_record_dataset_op.cc:390] TFRecordDataset `buffer_size` is unspecified, default to 262144
2025-12-03 21:01:49.331364: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-12-03 21:01:53.576113: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-12-03 21:01:57.317163: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-12-03 21:02:08.989857: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


Steps Per Epoch: 2382
Validation steps: 264


---
## Section 4: Model Definition and Warmup Phase

This section defines the architecture of the binary classification model based on the pre-trained EfficientNetV2B3 network with some surgery on it to accept our 4 channels input and executes the first stage of the multi-step fine-tuning process: the **Warmup Phase**.

### 4.1 The 4-Channel Input Strategy in Medical Deep Learning

For those new to medical AI, the **4-Channel (RGB + Mask)** approach is a sophisticated data-fusion technique. Instead of treating the lung image and the lung mask as separate entities, we bind them together into a single "super-image."

#### Why 4 Channels?
In traditional computer vision, we provide the model with a 3-channel (Red, Green, Blue) image. In a medical context, background noise—such as the heart silhouette, ribs, surgical cables, or the edge of the scan—can lead the model to "cheat" by finding patterns in regions that have nothing to do with the disease. 

By adding the **binary segmentation mask** as a 4th channel, we provide the model with an explicit anatomical map.

It's a famous appraoch with too many variants in medical AI and also other fileds on computer vision, for example this images using this method with special changes and also specific purposes in other tasks:

<div style="text-align: center;">
    <img src="../images/image-with-mask.png" alt="Crop with image and mask" style="display: block; margin: 0 auto;">
</div>

---
or in this example using this approach to remove mask(mask itself!) from face in face recognition and sensors stuff:

<div style="text-align: center;">
    <img src="../images/sensors.png" alt="Sensors face recognition without mask" style="display: block; margin: 0 auto;">
</div>


#### Advantages
* **Learned Spatial Attention:** The model doesn't just "see" the lung; it learns that the features *inside* the 4th channel's boundaries are high-priority, while features outside are low-priority.
* **Contextual Feature Extraction:** The model learns the relationship between the lung's texture (RGB) and its anatomical shape (Mask). This is particularly useful for detecting peripheral diseases that occur near the lung walls.
* **Preservation of Context:** Unlike "cropping" or "blacking out" the background (which creates artificial hard edges that can confuse a CNN), the 4th channel allows the model to see the whole image while knowing exactly where the "field of interest" is.
* **Robustness to Artifacts:** It significantly reduces "False Positives" caused by external artifacts like medical hardware or anatomical variations outside the lungs.

#### Disadvantages & Challenges
* **Architectural Complexity:** You cannot use standard off-the-shelf models without "surgery" (as seen in Section 3.2). This requires manual weight manipulation to maintain pre-trained benefits.
* **Dependency on Segmentation Quality:** The classifier is only as good as the mask. If the mask is poorly generated (cutting off part of a consolidation), the model may ignore critical diagnostic evidence.
* **Increased Memory Footprint:** Processing 4 channels instead of 3 increases the memory usage of the input tensors, which can be a factor when training on limited hardware.

---

#### Scientific Foundations and References
This method is widely utilized in state-of-the-art medical research. Below are key papers and concepts utilizing similar multi-channel or mask-guided attention strategies:

1.  **[Attention U-Net: Learning Where to Look for the Pancreas](https://arxiv.org/abs/1804.03999)** - Foundational paper explaining why "mask-like" attention is vital for medical imaging.
2.  **[Deep Learning for Lung Cancer Prognosis, Using 3D CNNs and Mask-Guided Attention](https://www.nature.com/articles/s41598-019-42523-x)** - A study in *Nature* showing how masks guide classification performance in pulmonary diagnostics.
3.  **[Mask-Guided Convolutional Neural Network for Breast Cancer Segmentation and Classification](https://ieeexplore.ieee.org/document/8759523)** - Demonstrates using masks as a constraint to improve classification accuracy.
4.  **[Anatomy-Aware Deep Learning for Medical Image Analysis](https://arxiv.org/abs/2101.01140)** - A comprehensive review of how anatomical context improves model generalizability.

By implementing this 4-channel strategy, our EfficientNetV2B3 model moves beyond simple pattern recognition and begins to perform "anatomy-aware" feature extraction.

---

### 4.2 Custom Model Architecture (`lung_efficientnet_model` function)

This function defines the core architecture of the diagnostic tool. It performs a sophisticated "weight surgery" on the **EfficientNetV2B3** backbone to accommodate the **4-channel input strategy** (RGB + Mask) while preserving the high-value feature extraction capabilities learned from the ImageNet dataset.

#### The Architectural Challenge: The "3-to-4 Channel" Problem
Standard pre-trained models are hard-coded for 3-channel (RGB) inputs. Simply changing the input shape to 4 channels usually forces the model to initialize with random weights, losing the benefit of pre-training. This function overcomes that limitation by manually rebuilding the first convolutional layer.

Let's first look at EfficeintNetV2 architecture:


<div style="text-align: center;">
    <img src="../images/Structure-of-EfficientNetV2.png" alt="EfficientNetV2 Structure" style="display: block; margin: 0 auto;">
</div>

---

#### Step-by-Step Breakdown of the "Model Surgery"

##### 1. Input Definition and Source Weights
The model is initialized with an input shape of $(256, 256, 4)$. To provide a source for the weights, the function first instantiates a temporary, standard 3-channel EfficientNetV2B3 model with `weights='imagenet'`.

##### 2. Kernel Surgery (The Critical Modification)
The function targets the very first layer of the network (named `input_conv`). It extracts the original 3-channel kernel, which has a shape of $[k, k, 3, \text{filters}]$. 

To create the 4th channel (the Mask channel), it uses an **Average Weight Initialization** strategy:
$$\text{Kernel}_{\text{Channel 4}} = \frac{1}{3} \sum_{c \in \{R, G, B\}} \text{Kernel}_c$$

The new 4-channel kernel is formed by concatenating this average with the original RGB weights:
$$\text{Kernel}_{\text{4-Channel}} = [\text{Kernel}_R, \text{Kernel}_G, \text{Kernel}_B, \text{Kernel}_{\text{Channel 4}}]$$

**Why average the weights?** This ensures the model starts with a balanced, non-random sensitivity to the mask's intensity, preventing the "gradient shock" that occurs when a new channel is initialized with random noise. It allows the model to immediately utilize its pre-trained understanding of image edges and textures while incorporating the mask.

##### 3. Weight Injection and Backbone Assembly
A "blank" 4-channel EfficientNetV2B3 is created (with `weights=None`). The function then:
* Injects the **surgically modified 4-channel kernel** into the first layer.
* Copies the bias weights from the original layer to maintain the activation baseline.
* Runs a loop to copy the weights of **every remaining layer** (from index 2 to the end) from the 3-channel model to the 4-channel model.

##### 4. Freezing Strategy and Batch Normalization
The backbone is initially set to `trainable = False`. Crucially, the function ensures all **BatchNormalization** layers are frozen:
* This prevents the pre-trained moving averages and variances from being corrupted during the initial training phases, maintaining the stability of the deep feature maps.

---

##### 5. Custom Classification Head
Once the 4-channel backbone is assembled, a custom head is attached to translate deep features into a binary health prediction:
1.  **Global Average Pooling (GAP):** Reduces the spatial dimensions to a single vector, providing a global representation of the lung parenchyma.
2.  **Dense 512 (ReLU):** A high-capacity fully connected layer to interpret complex features.
3.  **Dropout (0.4):** A robust regularization layer to prevent overfitting on specific lung textures.
4.  **Dense 64 (ReLU) + Dropout (0.3):** A secondary refinement stage to narrow down the feature space.
5.  **Output Layer (Sigmoid):** Produces a final probability score where $\approx 0$ represents **Healthy** and $\approx 1$ represents **Unhealthy**.

#### Clinical Goal of this Architecture
By merging the image and mask at the very first layer, the model is architecturally forced to learn **Mask-Image correlations**. Instead of looking for patterns across the whole image, the filters are conditioned by the 4th channel to prioritize pathological textures (like opacities or consolidations) specifically within the anatomical boundaries of the lungs.

In [18]:
def lung_efficientnet_model(img_size):
    '''
    Creates an EfficientNetV2B3 model modified to accept 4 input channels 
    (RGB Image + 1 Mask Channel) while retaining pre-trained ImageNet weights.

    This function performs "weight surgery" by averaging the original 3-channel 
    kernels to initialize the 4th channel, then injects these weights into a 
    new backbone while keeping subsequent layers pre-trained.

    Args:
        img_size (tuple): The spatial dimensions of the input (height, width).

    Returns:
        tf.keras.Model: A compiled-ready Keras model with a custom classification 
                        head and a 4-channel anatomy-aware backbone.
    '''
    # --- 1. Define the 4-Channel Input ---
    inputs = tf.keras.Input(shape= img_size + (4,))

    # --- 2. Handle 4-Channel Weight Modification (The Critical Part) ---
    
    # A. Load a temporary 3-channel model with ImageNet weights to extract the kernel
    base_model_3ch_original = EfficientNetV2B3(
        weights='imagenet',
        include_top=False,
        include_preprocessing=False,
        input_shape=img_size + (3,)
    )
    
    # B. Extract the weights for the very first convolutional layer ('input_conv')
    first_conv_layer_name = base_model_3ch_original.layers[1].name
    original_conv_layer = base_model_3ch_original.get_layer(first_conv_layer_name)
    
    # Get all weights (kernel is weights[0], bias may be weights[1])
    weights = original_conv_layer.get_weights()
    original_kernel = weights[0] # This will always be the kernel

    # C. Create the new 4-channel kernel
    
    # Average the weights across the 3 input channels to create the weights for the new 4th channel.
    new_channel_weights = tf.reduce_mean(original_kernel, axis=2, keepdims=True)
    
    # Concatenate the new channel weights to the original kernel
    new_kernel = tf.concat([original_kernel, new_channel_weights], axis=2)
    
    # --- 3. Instantiate the FINAL 4-Channel Base Model ---
    
    base_model_4ch = EfficientNetV2B3(
        weights=None,  # Do not load weights yet
        include_top=False,
        include_preprocessing=False,
        input_shape=img_size + (4,),
        name='efficientnetv2-b3'
    )

    # D. Set the modified weights for the first layer of the 4-channel model
    modified_conv_layer = base_model_4ch.get_layer(first_conv_layer_name)

    # Create the new weights list:
    new_weights = [new_kernel.numpy()]
    if len(weights) == 2:
        # If the original layer had a bias, append it to the new weights list
        new_weights.append(weights[1]) 
    
    # Set the modified weights (kernel only, or kernel + bias)
    modified_conv_layer.set_weights(new_weights)
    
    # Load all remaining pre-trained weights from the original 3ch model
    # We skip the first layer (index 1) which we handled manually
    for i in range(2, len(base_model_4ch.layers)):
        base_model_4ch.layers[i].set_weights(base_model_3ch_original.layers[i].get_weights())
        
    # --- 4. Define Training and Freezing Strategy ---
    
    base_model_4ch.trainable = False
    
    for layer in base_model_4ch.layers:
        if isinstance(layer, tf.keras.layers.BatchNormalization):
            layer.trainable = False

    # --- 5. Build the Classification Head ---
    eff = base_model_4ch(inputs, training=False) 
    gap = tfl.GlobalAveragePooling2D()(eff)
    fc1 = tfl.Dense(512, activation='relu')(gap)
    dp1 = tfl.Dropout(0.4)(fc1)
    fc2 = tfl.Dense(64, activation='relu')(dp1)
    dp2 = tfl.Dropout(0.3)(fc2)
    outputs = tfl.Dense(1, activation='sigmoid')(dp2)

    # create model object
    model = tf.keras.Model(inputs, outputs)
    # give model summary
    model.summary()
    
    del base_model_3ch_original 
    
    return model

### 4.3 Model Compilation and Warm-up Configuration

Now that we define the model and complete the first layer's surgery, we initializes the model within a distributed training scope and configure the optimization parameters specifically for the **Warm-up Phase**. During this stage, the backbone is frozen, allowing the custom classification head to adapt to the 4-channel features without distorting the pre-trained ImageNet weights.

#### Distributed Strategy and Optimization
* **Strategy Scope:** The model is instantiated within `strategy.scope()` to ensure that variables and computations are distributed across all available hardware.
* **AdamW Optimizer:** We utilize **Adam with Weight Decay (AdamW)**. This is specialized for EfficientNetV2 architectures as it decouples weight decay from the gradient updates, leading to better regularization and generalization.
    * **Warm-up LR:** A conservative learning rate is used to stabilize the initial training of the randomly initialized dense layers.
* **Label Smoothing (0.01):** Applied within the `BinaryCrossentropy` loss to prevent the model from becoming overconfident. This encourages the model to be more adaptable and improves performance on ambiguous or borderline clinical cases.

#### Diagnostic Evaluation Metrics
Since this is a medical classification task, we prioritize metrics that reflect clinical utility:
* **Recall (Sensitivity):** Our primary priority; it ensures we minimize "False Negatives" to avoid missing unhealthy cases.
* **Precision:** Ensures that "Unhealthy" predictions are accurate, reducing unnecessary follow-up procedures for healthy patients.
* **AUC (Area Under Curve):** Measures the model's overall discriminatory power across all possible classification thresholds.

In [19]:
with strategy.scope():
    # Initialize the 4-channel model within distributed strategy scope
    model = lung_efficientnet_model(IMAGE_SIZE)
    
    # Use label smoothing to prevent overconfidence and improve generalization
    loss = tf.keras.losses.BinaryCrossentropy(label_smoothing=0.01)
    
    # AdamW decouples weight decay for better regularization of the backbone
    optimizer = tf.keras.optimizers.AdamW(
        learning_rate=WARMUP_LR,
        weight_decay=1e-4,
        beta_1=0.9,
        beta_2=0.999,
        epsilon=1e-7
    )
    
    # Define clinical metrics; prioritizing Recall and AUC for screening accuracy
    metrics = [
        metrics.BinaryAccuracy(name='accuracy'),
        metrics.Recall(name='recall'),
        metrics.Precision(name='precision'),
        metrics.AUC(name='auc', multi_label=False),
    ]
    
    # Finalize configuration for the Warm-up phase
    model.compile(
        loss=loss,
        optimizer=optimizer,
        metrics=metrics
    )

/home/a1mohamad/ai-env/lib/python3.12/site-packages/keras/src/applications/efficientnet_v2.py:911: UserWarning: This model usually expects 1 or 3 input channels. However, it was passed an input_shape with 4 input channels.
  input_shape = imagenet_utils.obtain_input_shape(


Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 256, 256, 4)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ efficientnetv2-b3 (Functional)  │ (None, 8, 8, 1536)     │    12,930,982 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d        │ (None, 1536)           │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 512)            │       786,944 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │        32,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13,750,823 (52.46 MB)

 Trainable params: 819,841 (3.13 MB)

 Non-trainable params: 12,930,982 (49.33 MB)

---

### 3.4 Warm-up Training Callbacks

To manage the training process and capture the most robust model state, a suite of automated callbacks is implemented. These act as "safety nets" during the warm-up period to ensure stability and prevent resource waste.

| Callback | Primary Function | Logic & Patience |
| :--- | :--- | :--- |
| **ModelCheckpoint** | **Save Best Weights** | Monitors `val_loss` and preserves only the version of the model that achieves the lowest error. This ensures we don't use a degraded version if the model begins to overfit. |
| **EarlyStopping** | **Prevent Overfitting** | Stops training if `val_loss` fails to improve for **4 consecutive epochs**, reverting the model to its "best" state. |
| **ReduceLROnPlateau** | **Dynamic LR Tuning** | If the loss plateaus for **2 epochs**, the learning rate is multiplied by **0.66**. This allows the optimizer to "squeeze" out extra performance by taking smaller, more precise steps. |

In [20]:
# Save the best model based on validation loss
checkpoint_cb = ModelCheckpoint(
    warmup_efficientnet_path, # File to save the best model
    monitor='val_loss',
    save_best_only=True,
    mode='min' # We want to minimize loss
)

# Stop training if validation loss doesn't improve for 4 epochs
early_stopping_cb = EarlyStopping(
    monitor='val_loss',
    patience= 4,
    restore_best_weights=True
)

# Reduce learning rate when learning plateaus
reduce_lr_cb = ReduceLROnPlateau(
    monitor= 'val_loss',
    factor= 0.66,
    patience= 2,
    min_lr= 1e-5
)
# concatenate all callbacks
callbacks = [checkpoint_cb, early_stopping_cb, reduce_lr_cb]

Ok, now let's train our warmup phase!, for that, we use `INITIAL_EPOCH`, defined `steps_per_epoch` and `validation_steps` with datasets on `.repeat()` to ensure steps of training on every epoch, and also our `callbacks`, in a **history** object.

In [21]:
# Train warmup phase
history = model.fit(
    train_dataset.repeat(),
    epochs= INITIAL_EPOCH,
    validation_data= val_dataset.repeat(),
    steps_per_epoch= steps_per_epoch,
    validation_steps= validation_steps,
    callbacks= callbacks
)

INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Redu

E0000 00:00:1764691170.589017     411 meta_optimizer.cc:967] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape inStatefulPartitionedCall/functional_1_1/efficientnetv2-b3_1/block1b_drop_1/stateless_dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer
2025-12-02 19:29:33.943284: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:473] Loaded cuDNN version 91300


2381/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.7877 - auc: 0.8663 - loss: 0.4568 - precision: 0.8024 - recall: 0.7862

2025-12-02 19:33:30.994757: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 280s 111ms/step - accuracy: 0.8227 - auc: 0.8990 - loss: 0.4100 - precision: 0.8416 - recall: 0.8125 - val_accuracy: 0.8632 - val_auc: 0.9356 - val_loss: 0.3336 - val_precision: 0.9123 - val_recall: 0.8021 - learning_rate: 3.0000e-04
Epoch 2/10
2381/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.8497 - auc: 0.9216 - loss: 0.3630 - precision: 0.8735 - recall: 0.8305

2025-12-02 19:37:53.698700: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.8497 - auc: 0.9216 - loss: 0.3630 - precision: 0.8735 - recall: 0.8305

2025-12-02 19:38:15.017636: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 257s 108ms/step - accuracy: 0.8550 - auc: 0.9255 - loss: 0.3558 - precision: 0.8787 - recall: 0.8371 - val_accuracy: 0.8684 - val_auc: 0.9376 - val_loss: 0.3244 - val_precision: 0.8900 - val_recall: 0.8392 - learning_rate: 3.0000e-04
Epoch 3/10
2379/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.8643 - auc: 0.9331 - loss: 0.3380 - precision: 0.8858 - recall: 0.8473

2025-12-02 19:42:04.103064: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.8643 - auc: 0.9331 - loss: 0.3380 - precision: 0.8858 - recall: 0.8473

2025-12-02 19:42:23.457660: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 247s 103ms/step - accuracy: 0.8635 - auc: 0.9339 - loss: 0.3368 - precision: 0.8862 - recall: 0.8466 - val_accuracy: 0.8845 - val_auc: 0.9487 - val_loss: 0.3002 - val_precision: 0.9138 - val_recall: 0.8478 - learning_rate: 3.0000e-04
Epoch 4/10
2379/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.8657 - auc: 0.9361 - loss: 0.3309 - precision: 0.8901 - recall: 0.8462

2025-12-02 19:46:16.938076: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 251s 105ms/step - accuracy: 0.8662 - auc: 0.9371 - loss: 0.3283 - precision: 0.8903 - recall: 0.8476 - val_accuracy: 0.8722 - val_auc: 0.9456 - val_loss: 0.3140 - val_precision: 0.9353 - val_recall: 0.7983 - learning_rate: 3.0000e-04
Epoch 5/10
2378/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.8709 - auc: 0.9388 - loss: 0.3258 - precision: 0.8942 - recall: 0.8515

2025-12-02 19:50:31.740371: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.8709 - auc: 0.9388 - loss: 0.3258 - precision: 0.8942 - recall: 0.8515

2025-12-02 19:50:51.933950: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 255s 107ms/step - accuracy: 0.8730 - auc: 0.9409 - loss: 0.3216 - precision: 0.8943 - recall: 0.8573 - val_accuracy: 0.8878 - val_auc: 0.9495 - val_loss: 0.3045 - val_precision: 0.8762 - val_recall: 0.9020 - learning_rate: 3.0000e-04
Epoch 6/10
2376/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.8741 - auc: 0.9437 - loss: 0.3127 - precision: 0.8941 - recall: 0.8598

2025-12-02 19:55:06.948776: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.8741 - auc: 0.9437 - loss: 0.3127 - precision: 0.8941 - recall: 0.8599

2025-12-02 19:55:29.407856: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 281s 118ms/step - accuracy: 0.8782 - auc: 0.9456 - loss: 0.3088 - precision: 0.8979 - recall: 0.8645 - val_accuracy: 0.8793 - val_auc: 0.9536 - val_loss: 0.2929 - val_precision: 0.9270 - val_recall: 0.8221 - learning_rate: 1.9800e-04
Epoch 7/10
2376/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.8798 - auc: 0.9466 - loss: 0.3060 - precision: 0.8999 - recall: 0.8651

2025-12-02 19:59:28.848922: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.8798 - auc: 0.9466 - loss: 0.3060 - precision: 0.8999 - recall: 0.8651

2025-12-02 19:59:51.464862: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 278s 116ms/step - accuracy: 0.8806 - auc: 0.9479 - loss: 0.3023 - precision: 0.8982 - recall: 0.8693 - val_accuracy: 0.8958 - val_auc: 0.9548 - val_loss: 0.2828 - val_precision: 0.9014 - val_recall: 0.8877 - learning_rate: 1.9800e-04
Epoch 8/10
2375/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.8840 - auc: 0.9509 - loss: 0.2943 - precision: 0.8994 - recall: 0.8742

2025-12-02 20:04:04.609533: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.8840 - auc: 0.9509 - loss: 0.2943 - precision: 0.8994 - recall: 0.8742

2025-12-02 20:04:26.456281: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 263s 110ms/step - accuracy: 0.8842 - auc: 0.9494 - loss: 0.2981 - precision: 0.9010 - recall: 0.8738 - val_accuracy: 0.8944 - val_auc: 0.9565 - val_loss: 0.2782 - val_precision: 0.9019 - val_recall: 0.8839 - learning_rate: 1.9800e-04
Epoch 9/10
2374/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.8816 - auc: 0.9506 - loss: 0.2954 - precision: 0.9014 - recall: 0.8666

2025-12-02 20:08:20.324959: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.8816 - auc: 0.9506 - loss: 0.2954 - precision: 0.9014 - recall: 0.8666

2025-12-02 20:08:40.612498: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 247s 104ms/step - accuracy: 0.8808 - auc: 0.9501 - loss: 0.2967 - precision: 0.8996 - recall: 0.8679 - val_accuracy: 0.8949 - val_auc: 0.9546 - val_loss: 0.2875 - val_precision: 0.8907 - val_recall: 0.8991 - learning_rate: 1.9800e-04
Epoch 10/10
2372/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.8860 - auc: 0.9513 - loss: 0.2926 - precision: 0.9043 - recall: 0.8725

2025-12-02 20:12:27.502515: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.8860 - auc: 0.9513 - loss: 0.2926 - precision: 0.9043 - recall: 0.8724

2025-12-02 20:12:48.002070: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 247s 104ms/step - accuracy: 0.8834 - auc: 0.9500 - loss: 0.2959 - precision: 0.9029 - recall: 0.8694 - val_accuracy: 0.8868 - val_auc: 0.9536 - val_loss: 0.2971 - val_precision: 0.9356 - val_recall: 0.8297 - learning_rate: 1.9800e-04


---
## 5. Mid-Tune Phase: Strategic Backbone Refinement

The **Mid-Tune phase** serves as the critical bridge between initial head training and final model optimization. In this stage, we surgically "thaw" the deeper sections of the **EfficientNetV2B3** backbone. This allows the high-level feature extractors to specialize in identifying complex pulmonary pathologies within the 4-channel input space while leveraging pre-trained ImageNet foundations.

---

### 5.1.1 Selective Unfreezing and BN Preservation

The Mid-Tune strategy focuses on a top-down refinement, ensuring that fundamental low-level filters remain intact while complex diagnostic filters are updated.

* **Mid-Tune Entry Point:** We define `block6a_expand_conv` as the architectural boundary. All layers from this block to the output are set to `trainable = True`.
* **Anatomical Reasoning:** The early layers of a CNN detect basic edges and textures. By keeping them frozen, we prevent the model from losing its robust general-purpose vision. 
* **The BN Constraint:** A critical rule of Mid-Tuning is keeping **BatchNormalization layers frozen** (`trainable = False`). This prevents the pre-trained ImageNet distribution statistics from being overwritten by the smaller clinical dataset, which is a common cause of training instability and "divergent" gradients.



---

### 5.1.2 Advanced Optimization: The Logic of Cosine Decay

A `tf.keras.optimizers.schedules.CosineDecay` schedule is introduced to manage the learning rate during this phase, promoting stable and optimized convergence.

<div style="text-align: center;">
    <img src="../images/cosine_decay.png" alt="Cosine Decay Learning Rate Schedule" style="display: block; margin: 0 auto;">
</div>


In standard training, a static learning rate or a "step" decay (dropping the rate by half every 10 epochs) is often used. However, for a surgical phase like Mid-Tuning, these methods are often too abrupt. Cosine Decay offers a smoother, more "human-like" approach to learning.

#### How it Works
The learning rate follows the curve of a cosine function, specifically the segment from $0$ to $\pi$:

$$\eta_t = \eta_{min} + \frac{1}{2}(\eta_{max} - \eta_{min})\left(1 + \cos\left(\frac{T_{cur}}{T_{max}}\pi\right)\right)$$

**Where:**
* $\eta_t$: Learning rate at the current step.
* $\eta_{max}$: Initial `BACKBONE_WARMUP_LR`.
* $T_{max}$: Total steps in the Mid-Tune phase.



#### Key Advantages in Medical AI
* **Avoidance of Gradient Shock:** Step decay creates "shocks" in the weight updates when the rate suddenly drops. In Mid-Tuning, where we are trying to preserve pre-trained knowledge, these shocks can cause the model to lose fine-grained details. Cosine decay's infinitesimal changes at each step keep the training stable.
* **The "Slow Settling" Effect:** As the curve nears the end of the phase, the learning rate becomes extremely small (our 10% alpha). This allows the model to "settle" into the deepest, narrowest valleys of the loss landscape, finding optimal weights that a faster, clunkier optimizer would simply skip over.
* **Improved Generalization:** Research shows that models trained with cosine schedules often generalize better to unseen test data. By starting relatively "warm" and cooling down slowly, the model explores the weight space more thoroughly before committing to a final state.
* **No Hyperparameter Tuning for "When" to Drop:** With step decay, you have to guess when to drop the rate. Cosine decay automates this; it is always decreasing, ensuring that every batch is processed with a slightly more refined precision than the last.

#### Decoupled Weight Decay (AdamW)
By using **AdamW**, we ensure that weight decay (regularization) is decoupled from the learning rate updates. This is vital during Mid-Tuning because it keeps the backbone weights from growing chaotic or over-fitting, even as the learning rate floor is reached.

#### 📄 Scientific Source
This method was popularized by the influential paper: **[SGDR: Stochastic Gradient Descent with Warm Restarts](https://arxiv.org/abs/1608.03983)**. While we aren't using "restarts" here, the cosine annealing schedule proposed in this paper has become the gold standard for fine-tuning architectures like EfficientNet.

---

In [18]:
with strategy.scope():
    # Load the best model from the head-only warm-up phase
    model = tf.keras.models.load_model(warmup_efficientnet_path)
    base_model = model.get_layer('efficientnetv2-b3')
    
    # Enter Mid-Tune: Unfreeze from block 6 to the output
    mid_tune_layer = 'block6a_expand_conv'
    unfreeze = False
    
    for layer in base_model.layers:
        if layer.name == mid_tune_layer:
            unfreeze = True
        
        if unfreeze:
            # BN layers remain frozen to protect ImageNet statistics during mid-tuning
            if isinstance(layer, tf.keras.layers.BatchNormalization):
                layer.trainable = False
            else:
                layer.trainable = True
    
    # Calculate steps for the smooth Cosine Decay schedule
    total_training_steps = steps_per_epoch * (MIDTUNE_EPOCH - INITIAL_EPOCH)
    cosine_decay = tf.keras.optimizers.schedules.CosineDecay(
        initial_learning_rate=BACKBONE_WARMUP_LR,
        decay_steps=total_training_steps,
        alpha=0.1 # Settle at 10% of the initial LR
    )

    # Re-compile with AdamW and the Cosine schedule
    model.compile(
        loss=tf.keras.losses.BinaryCrossentropy(label_smoothing=0.05),
        optimizer=tf.keras.optimizers.AdamW(learning_rate=cosine_decay, weight_decay=1e-4),
        metrics=[
            metrics.BinaryAccuracy(name='accuracy'),
            metrics.Recall(name='recall'),
            metrics.Precision(name='precision'),
            metrics.AUC(name='AUC', multi_label=False)
        ]
    )


### 5.2 Mid-Tune Monitoring and Callbacks

The Mid-Tune phase requires more "patience" than the warm-up because adjusting deep backbone weights takes more time to reflect in the loss landscape.

| Callback | Role in Mid-Tune | Technical Parameter |
| :--- | :--- | :--- |
| **EarlyStopping** | **Prevent Overfitting** | **Patience = 7**: Allows the model more time to navigate "learning plateaus" before declaring the phase complete. |
| **TensorBoard** | **Audit Trail** | Essential for tracking weight histograms and gradient flow to ensure the 4-channel integration is healthy. |
| **ModelCheckpoint** | **Validation Shield** | Continuously monitors `val_loss` to ensure we preserve the absolute best iteration of the model. |

In [19]:
# Save the best model based on validation loss
checkpoint_cb = ModelCheckpoint(
    midtune_efficientnet_path, # File to save the best model
    monitor= 'val_loss',
    save_best_only= True,
    mode= 'min' # We want to minimize loss
)

# Stop training if validation loss doesn't improve for 7 epochs
early_stopping_cb = EarlyStopping(
    monitor= 'val_loss',
    patience= 7,
    restore_best_weights= True
)
# Save a TensorBoard object if you want visualize training progress
tb_cb = TensorBoard(
    log_dir= '../logs/classification/efficientnet/',
    histogram_freq= 1
)
# Concatenate all callbacks
callbacks = [checkpoint_cb, early_stopping_cb, tb_cb]

In [20]:
# Execute Mid-Tune phase
history = model.fit(
    train_dataset.repeat(),
    initial_epoch= INITIAL_EPOCH,
    epochs= MIDTUNE_EPOCH,
    validation_data= val_dataset.repeat(),
    steps_per_epoch= steps_per_epoch,
    validation_steps= validation_steps,
    callbacks= callbacks
)

INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Redu

E0000 00:00:1764696288.204214     414 meta_optimizer.cc:967] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape inStatefulPartitionedCall/functional_1_1/efficientnetv2-b3_1/block1b_drop_1/stateless_dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer
2025-12-02 20:54:55.604169: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:473] Loaded cuDNN version 91300


2381/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - AUC: 0.9535 - accuracy: 0.8870 - loss: 0.3398 - precision: 0.9075 - recall: 0.8712

2025-12-02 21:01:14.947253: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - AUC: 0.9535 - accuracy: 0.8870 - loss: 0.3398 - precision: 0.9075 - recall: 0.8712

2025-12-02 21:01:42.757659: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 434s 173ms/step - AUC: 0.9564 - accuracy: 0.8926 - loss: 0.3317 - precision: 0.9145 - recall: 0.8758 - val_AUC: 0.9634 - val_accuracy: 0.8987 - val_loss: 0.3204 - val_precision: 0.8871 - val_recall: 0.9125
Epoch 12/30
2380/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - AUC: 0.9610 - accuracy: 0.9035 - loss: 0.3169 - precision: 0.9218 - recall: 0.8889

2025-12-02 21:08:02.020627: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - AUC: 0.9610 - accuracy: 0.9035 - loss: 0.3169 - precision: 0.9218 - recall: 0.8889

2025-12-02 21:08:22.843799: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 400s 168ms/step - AUC: 0.9630 - accuracy: 0.9048 - loss: 0.3122 - precision: 0.9238 - recall: 0.8907 - val_AUC: 0.9697 - val_accuracy: 0.9100 - val_loss: 0.2957 - val_precision: 0.9517 - val_recall: 0.8630
Epoch 13/30
2379/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - AUC: 0.9680 - accuracy: 0.9108 - loss: 0.2976 - precision: 0.9305 - recall: 0.8948

2025-12-02 21:14:43.112321: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - AUC: 0.9680 - accuracy: 0.9108 - loss: 0.2976 - precision: 0.9305 - recall: 0.8948

2025-12-02 21:15:04.068286: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 410s 172ms/step - AUC: 0.9684 - accuracy: 0.9105 - loss: 0.2966 - precision: 0.9275 - recall: 0.8984 - val_AUC: 0.9754 - val_accuracy: 0.9228 - val_loss: 0.2762 - val_precision: 0.9205 - val_recall: 0.9248
Epoch 14/30
2378/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - AUC: 0.9708 - accuracy: 0.9152 - loss: 0.2893 - precision: 0.9296 - recall: 0.9055

2025-12-02 21:21:37.054222: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - AUC: 0.9708 - accuracy: 0.9152 - loss: 0.2893 - precision: 0.9296 - recall: 0.9055

2025-12-02 21:21:58.227245: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 409s 172ms/step - AUC: 0.9708 - accuracy: 0.9154 - loss: 0.2886 - precision: 0.9295 - recall: 0.9062 - val_AUC: 0.9744 - val_accuracy: 0.9247 - val_loss: 0.2734 - val_precision: 0.9313 - val_recall: 0.9163
Epoch 15/30
2377/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - AUC: 0.9741 - accuracy: 0.9233 - loss: 0.2767 - precision: 0.9372 - recall: 0.9139

2025-12-02 21:28:24.212106: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - AUC: 0.9741 - accuracy: 0.9232 - loss: 0.2767 - precision: 0.9372 - recall: 0.9139

2025-12-02 21:28:44.631069: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 407s 171ms/step - AUC: 0.9742 - accuracy: 0.9218 - loss: 0.2769 - precision: 0.9352 - recall: 0.9130 - val_AUC: 0.9782 - val_accuracy: 0.9280 - val_loss: 0.2607 - val_precision: 0.9285 - val_recall: 0.9267
Epoch 16/30
2376/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - AUC: 0.9752 - accuracy: 0.9226 - loss: 0.2730 - precision: 0.9362 - recall: 0.9131

2025-12-02 21:35:13.168530: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - AUC: 0.9752 - accuracy: 0.9226 - loss: 0.2729 - precision: 0.9362 - recall: 0.9131

2025-12-02 21:35:33.596406: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 407s 171ms/step - AUC: 0.9768 - accuracy: 0.9248 - loss: 0.2685 - precision: 0.9385 - recall: 0.9157 - val_AUC: 0.9782 - val_accuracy: 0.9295 - val_loss: 0.2587 - val_precision: 0.9457 - val_recall: 0.9106
Epoch 17/30
2375/2382 ━━━━━━━━━━━━━━━━━━━━ 1s 157ms/step - AUC: 0.9769 - accuracy: 0.9298 - loss: 0.2664 - precision: 0.9450 - recall: 0.9178

2025-12-02 21:42:01.381527: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - AUC: 0.9769 - accuracy: 0.9298 - loss: 0.2664 - precision: 0.9450 - recall: 0.9178

2025-12-02 21:42:23.211842: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 410s 172ms/step - AUC: 0.9784 - accuracy: 0.9302 - loss: 0.2626 - precision: 0.9443 - recall: 0.9203 - val_AUC: 0.9790 - val_accuracy: 0.9347 - val_loss: 0.2557 - val_precision: 0.9579 - val_recall: 0.9087
Epoch 18/30
2374/2382 ━━━━━━━━━━━━━━━━━━━━ 1s 168ms/step - AUC: 0.9793 - accuracy: 0.9350 - loss: 0.2562 - precision: 0.9477 - recall: 0.9259

2025-12-02 21:49:18.355158: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - AUC: 0.9793 - accuracy: 0.9350 - loss: 0.2562 - precision: 0.9477 - recall: 0.9259

2025-12-02 21:49:42.998017: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 453s 190ms/step - AUC: 0.9793 - accuracy: 0.9342 - loss: 0.2569 - precision: 0.9464 - recall: 0.9260 - val_AUC: 0.9803 - val_accuracy: 0.9380 - val_loss: 0.2507 - val_precision: 0.9519 - val_recall: 0.9220
Epoch 19/30
2373/2382 ━━━━━━━━━━━━━━━━━━━━ 1s 168ms/step - AUC: 0.9800 - accuracy: 0.9351 - loss: 0.2538 - precision: 0.9481 - recall: 0.9256

2025-12-02 21:56:49.445479: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - AUC: 0.9800 - accuracy: 0.9351 - loss: 0.2538 - precision: 0.9481 - recall: 0.9256

2025-12-02 21:57:11.413564: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 434s 182ms/step - AUC: 0.9804 - accuracy: 0.9357 - loss: 0.2532 - precision: 0.9481 - recall: 0.9274 - val_AUC: 0.9812 - val_accuracy: 0.9380 - val_loss: 0.2472 - val_precision: 0.9609 - val_recall: 0.9125
Epoch 20/30
2372/2382 ━━━━━━━━━━━━━━━━━━━━ 1s 166ms/step - AUC: 0.9811 - accuracy: 0.9382 - loss: 0.2492 - precision: 0.9506 - recall: 0.9288

2025-12-02 22:03:59.697705: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 435s 183ms/step - AUC: 0.9814 - accuracy: 0.9371 - loss: 0.2492 - precision: 0.9494 - recall: 0.9288 - val_AUC: 0.9824 - val_accuracy: 0.9408 - val_loss: 0.2417 - val_precision: 0.9469 - val_recall: 0.9334
Epoch 21/30
2371/2382 ━━━━━━━━━━━━━━━━━━━━ 1s 159ms/step - AUC: 0.9824 - accuracy: 0.9390 - loss: 0.2466 - precision: 0.9537 - recall: 0.9277

2025-12-02 22:10:57.097445: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - AUC: 0.9824 - accuracy: 0.9390 - loss: 0.2466 - precision: 0.9537 - recall: 0.9277

2025-12-02 22:11:19.364746: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 414s 174ms/step - AUC: 0.9826 - accuracy: 0.9380 - loss: 0.2463 - precision: 0.9500 - recall: 0.9299 - val_AUC: 0.9828 - val_accuracy: 0.9432 - val_loss: 0.2395 - val_precision: 0.9632 - val_recall: 0.9210
Epoch 22/30
2370/2382 ━━━━━━━━━━━━━━━━━━━━ 1s 158ms/step - AUC: 0.9827 - accuracy: 0.9402 - loss: 0.2437 - precision: 0.9509 - recall: 0.9324

2025-12-02 22:17:49.477656: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - AUC: 0.9827 - accuracy: 0.9402 - loss: 0.2437 - precision: 0.9509 - recall: 0.9324

2025-12-02 22:18:12.604882: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 404s 170ms/step - AUC: 0.9832 - accuracy: 0.9410 - loss: 0.2419 - precision: 0.9532 - recall: 0.9324 - val_AUC: 0.9829 - val_accuracy: 0.9403 - val_loss: 0.2419 - val_precision: 0.9667 - val_recall: 0.9115
Epoch 23/30
2369/2382 ━━━━━━━━━━━━━━━━━━━━ 2s 159ms/step - AUC: 0.9830 - accuracy: 0.9396 - loss: 0.2425 - precision: 0.9535 - recall: 0.9291

2025-12-02 22:24:36.061125: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - AUC: 0.9830 - accuracy: 0.9396 - loss: 0.2425 - precision: 0.9535 - recall: 0.9291

2025-12-02 22:24:57.983089: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 416s 175ms/step - AUC: 0.9839 - accuracy: 0.9431 - loss: 0.2392 - precision: 0.9558 - recall: 0.9339 - val_AUC: 0.9837 - val_accuracy: 0.9413 - val_loss: 0.2361 - val_precision: 0.9531 - val_recall: 0.9277
Epoch 24/30
2368/2382 ━━━━━━━━━━━━━━━━━━━━ 2s 157ms/step - AUC: 0.9833 - accuracy: 0.9439 - loss: 0.2387 - precision: 0.9535 - recall: 0.9376

2025-12-02 22:31:26.069843: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - AUC: 0.9833 - accuracy: 0.9439 - loss: 0.2387 - precision: 0.9535 - recall: 0.9376

2025-12-02 22:31:47.969060: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 397s 167ms/step - AUC: 0.9837 - accuracy: 0.9441 - loss: 0.2376 - precision: 0.9546 - recall: 0.9374 - val_AUC: 0.9833 - val_accuracy: 0.9432 - val_loss: 0.2419 - val_precision: 0.9716 - val_recall: 0.9125
Epoch 25/30
2367/2382 ━━━━━━━━━━━━━━━━━━━━ 2s 153ms/step - AUC: 0.9835 - accuracy: 0.9439 - loss: 0.2386 - precision: 0.9544 - recall: 0.9363

2025-12-02 22:37:55.092568: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - AUC: 0.9835 - accuracy: 0.9439 - loss: 0.2386 - precision: 0.9544 - recall: 0.9363

2025-12-02 22:38:16.591221: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 399s 167ms/step - AUC: 0.9840 - accuracy: 0.9448 - loss: 0.2370 - precision: 0.9556 - recall: 0.9376 - val_AUC: 0.9840 - val_accuracy: 0.9455 - val_loss: 0.2334 - val_precision: 0.9625 - val_recall: 0.9267
Epoch 26/30
2366/2382 ━━━━━━━━━━━━━━━━━━━━ 2s 153ms/step - AUC: 0.9852 - accuracy: 0.9495 - loss: 0.2312 - precision: 0.9618 - recall: 0.9398

2025-12-02 22:44:33.972258: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 389s 163ms/step - AUC: 0.9852 - accuracy: 0.9479 - loss: 0.2322 - precision: 0.9600 - recall: 0.9390 - val_AUC: 0.9841 - val_accuracy: 0.9465 - val_loss: 0.2359 - val_precision: 0.9699 - val_recall: 0.9210
Epoch 27/30
2365/2382 ━━━━━━━━━━━━━━━━━━━━ 2s 153ms/step - AUC: 0.9866 - accuracy: 0.9493 - loss: 0.2282 - precision: 0.9604 - recall: 0.9412

2025-12-02 22:51:02.154200: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - AUC: 0.9866 - accuracy: 0.9493 - loss: 0.2282 - precision: 0.9604 - recall: 0.9412

2025-12-02 22:51:23.828964: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 403s 169ms/step - AUC: 0.9867 - accuracy: 0.9482 - loss: 0.2283 - precision: 0.9587 - recall: 0.9410 - val_AUC: 0.9844 - val_accuracy: 0.9484 - val_loss: 0.2322 - val_precision: 0.9682 - val_recall: 0.9267
Epoch 28/30
2364/2382 ━━━━━━━━━━━━━━━━━━━━ 2s 155ms/step - AUC: 0.9853 - accuracy: 0.9488 - loss: 0.2309 - precision: 0.9602 - recall: 0.9410

2025-12-02 22:57:50.349217: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - AUC: 0.9853 - accuracy: 0.9488 - loss: 0.2308 - precision: 0.9602 - recall: 0.9410

2025-12-02 22:58:12.240058: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 393s 165ms/step - AUC: 0.9864 - accuracy: 0.9495 - loss: 0.2280 - precision: 0.9597 - recall: 0.9426 - val_AUC: 0.9844 - val_accuracy: 0.9474 - val_loss: 0.2323 - val_precision: 0.9663 - val_recall: 0.9267
Epoch 29/30
2363/2382 ━━━━━━━━━━━━━━━━━━━━ 2s 154ms/step - AUC: 0.9867 - accuracy: 0.9478 - loss: 0.2273 - precision: 0.9561 - recall: 0.9432

2025-12-02 23:04:21.545901: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - AUC: 0.9867 - accuracy: 0.9479 - loss: 0.2273 - precision: 0.9561 - recall: 0.9433

2025-12-02 23:04:43.648346: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 401s 168ms/step - AUC: 0.9865 - accuracy: 0.9496 - loss: 0.2274 - precision: 0.9582 - recall: 0.9442 - val_AUC: 0.9844 - val_accuracy: 0.9470 - val_loss: 0.2320 - val_precision: 0.9653 - val_recall: 0.9267
Epoch 30/30
2362/2382 ━━━━━━━━━━━━━━━━━━━━ 3s 155ms/step - AUC: 0.9861 - accuracy: 0.9503 - loss: 0.2285 - precision: 0.9616 - recall: 0.9426

2025-12-02 23:11:04.813703: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - AUC: 0.9861 - accuracy: 0.9503 - loss: 0.2285 - precision: 0.9616 - recall: 0.9426

2025-12-02 23:11:27.715149: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 406s 170ms/step - AUC: 0.9867 - accuracy: 0.9497 - loss: 0.2274 - precision: 0.9607 - recall: 0.9420 - val_AUC: 0.9844 - val_accuracy: 0.9470 - val_loss: 0.2318 - val_precision: 0.9662 - val_recall: 0.9258


---
## 6. Global Fine-Tuning: Full Model Unfreezing

The **Global Fine-Tuning phase** is the final and most intensive stage of the training pipeline. In this phase, we transition from partial backbone refinement to unfreezing the entire **EfficientNetV2B3** architecture. This allows every parameter in the network—from the initial 4-channel convolutional kernels to the final classification dense layers—to be co-optimized for the detection of lung pathologies.

---

### 6.1 Total Backbone Unfreezing and Stability Constraints

In this ultimate stage, we allow the gradients to flow through all 100+ layers of the model. This ensures that even the low-level filters (detecting simple edges and textures) are subtly adjusted to better interpret the specific intensities of 4-channel lung scans.

* **Global Trainability:** We set the entire `base_model.trainable = True`. This transforms the model from a pre-trained extractor into a fully specialized medical diagnostic tool.
* **The BatchNormalization Exception:** Even during total unfreezing, **BatchNormalization layers remain frozen** (`trainable = False`). 
    > **Why?** Re-training BN layers on a specialized, smaller dataset can cause "Internal Covariate Shift" and lead to unstable training. Keeping them in inference mode ensures we continue to benefit from the robust feature statistics learned during ImageNet pre-training.



---

### 6.2 Optimization Profile: Fine-Tune LR and Weight Decay

Because we are now modifying the entire weight space of the model, we use an extremely cautious and surgical optimization profile to prevent "Catastrophic Forgetting."

* **Fine-Tune Learning Rate:** We utilize an ultra-low `FINE_TUNE_LR`. This ensures that we only perform "nudge" updates to the weights, preserving the structural integrity of the pre-trained backbone.
* **Higher Weight Decay ($3 \times 10^{-4}$):** We increase the `weight_decay` in the AdamW optimizer. Since the whole model is now trainable, the risk of overfitting is at its highest. A stronger decay penalizes overly complex weight configurations, forcing the model to find simpler, more generalizable features.
* **Cosine Decay Extension:** The learning rate continues to follow a **Cosine Decay** curve, dropping to 10% of its initial fine-tuning value. This "cooling" process is essential for stabilizing the model as it converges on the global minimum of the loss landscape.

In [18]:
with strategy.scope():
    # Load the best-performing model from the Mid-Tune phase
    model = tf.keras.models.load_model(midtune_efficientnet_path)
    base_model = model.get_layer('efficientnetv2-b3')
    
    # Enable global trainability across the entire backbone
    base_model.trainable = True
    for layer in base_model.layers:
        # Maintain BN layers in inference mode to prevent statistic corruption
        if isinstance(layer, tf.keras.layers.BatchNormalization):
            layer.trainable = False
        else:
            layer.trainable = True
    
    # Calculate decay steps for the final global optimization period
    total_steps = steps_per_epoch * (UNFREEZE_EPOCH - MIDTUNE_EPOCH)

    # Use a surgical Fine-Tune LR with Cosine Decay for stable convergence
    cosine_decay = tf.keras.optimizers.schedules.CosineDecay(
        initial_learning_rate=FINE_TUNE_LR,
        decay_steps=total_steps,
        alpha=0.1
    )

    # Increase weight_decay (3e-4) to provide stronger regularization during full unfreezing
    optimizer = tf.keras.optimizers.AdamW(
        learning_rate=cosine_decay,
        weight_decay=3e-4,
        beta_1=0.9,
        beta_2=0.999,
        epsilon=1e-7
    )
    
    # Re-compile to apply the global training configuration
    model.compile(
        loss=tf.keras.losses.BinaryCrossentropy(label_smoothing=0.05),
        optimizer=optimizer,
        metrics=[
            metrics.BinaryAccuracy(name='accuracy'),
            metrics.Recall(name='recall'),
            metrics.Precision(name='precision'),
            metrics.AUC(name='AUC', multi_label=False)
        ]
    )

### 6.2 Monitoring and Final Checkpoints

The callbacks for this phase are tuned to capture the absolute peak performance of the network before any potential degradation occurs.

| Callback | Function | Implementation Logic |
| :--- | :--- | :--- |
| **ModelCheckpoint** | **Final Preservation** | Saves the state to `final_efficientnet_path`. This represents the most advanced version of the diagnostic tool. |
| **EarlyStopping** | **Best Weights Restoration** | Features a `patience = 5`. Crucially, it uses `restore_best_weights=True`, which automatically rewinds the model to its most accurate state if the training starts to drift. |
| **TensorBoard** | **Full Histogram Audit** | Records weight distributions for every layer. This allows us to verify that the "Global Unfreeze" did not cause any layer weights to explode or vanish. |

#### Training Progression
The `model.fit` call begins at `MIDTUNE_EPOCH` and progresses to `UNFREEZE_EPOCH`. This continuity allows the training history to be analyzed as a single, multi-stage evolution—from a general-purpose image classifier to an anatomy-aware pulmonary diagnostic system.

In [19]:
# Save the best model based on validation loss
checkpoint_cb = ModelCheckpoint(
    final_efficientnet_path, # File to save the best model
    monitor= 'val_loss',
    save_best_only= True,
    mode= 'min' # We want to minimize loss
)

# Stop training if validation loss doesn't improve for 5 epochs
early_stopping_cb = EarlyStopping(
    monitor= 'val_loss',
    patience= 5,
    restore_best_weights= True
)
# Save a TensorBoard object if you want visualize training progress
tb_cb = TensorBoard(
    log_dir= '../logs/classification/efficientnet',
    histogram_freq= 1
)
# Concatenate all callbacks
callbacks = [checkpoint_cb, early_stopping_cb, tb_cb]

In [20]:
# Execute Fine-Tune whole model
history = model.fit(
    train_dataset.repeat(),
    initial_epoch= MIDTUNE_EPOCH,
    epochs= UNFREEZE_EPOCH,
    validation_data= val_dataset.repeat(),
    steps_per_epoch= steps_per_epoch,
    validation_steps= validation_steps,
    callbacks= callbacks
)

INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Redu

E0000 00:00:1764783356.873642     474 meta_optimizer.cc:967] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape inStatefulPartitionedCall/functional_1_1/efficientnetv2-b3_1/block1b_drop_1/stateless_dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer
2025-12-03 21:06:03.629663: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:473] Loaded cuDNN version 91300


2380/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 272ms/step - AUC: 0.9870 - accuracy: 0.9487 - loss: 0.2263 - precision: 0.9592 - recall: 0.9411

2025-12-03 21:16:59.124020: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 273ms/step - AUC: 0.9870 - accuracy: 0.9487 - loss: 0.2263 - precision: 0.9592 - recall: 0.9411

2025-12-03 21:17:07.004006: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size
2025-12-03 21:17:26.775162: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 716s 290ms/step - AUC: 0.9868 - accuracy: 0.9493 - loss: 0.2269 - precision: 0.9603 - recall: 0.9414 - val_AUC: 0.9845 - val_accuracy: 0.9498 - val_loss: 0.2293 - val_precision: 0.9655 - val_recall: 0.9324
Epoch 32/130
2379/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 273ms/step - AUC: 0.9870 - accuracy: 0.9508 - loss: 0.2253 - precision: 0.9611 - recall: 0.9437

2025-12-03 21:28:30.580232: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 273ms/step - AUC: 0.9870 - accuracy: 0.9508 - loss: 0.2253 - precision: 0.9611 - recall: 0.9438

2025-12-03 21:28:51.430915: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 675s 283ms/step - AUC: 0.9865 - accuracy: 0.9507 - loss: 0.2269 - precision: 0.9597 - recall: 0.9451 - val_AUC: 0.9847 - val_accuracy: 0.9493 - val_loss: 0.2299 - val_precision: 0.9692 - val_recall: 0.9277
Epoch 33/130
2379/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 271ms/step - AUC: 0.9868 - accuracy: 0.9491 - loss: 0.2262 - precision: 0.9627 - recall: 0.9380

2025-12-03 21:39:39.941204: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 271ms/step - AUC: 0.9868 - accuracy: 0.9491 - loss: 0.2262 - precision: 0.9627 - recall: 0.9380

2025-12-03 21:40:00.875868: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 674s 283ms/step - AUC: 0.9867 - accuracy: 0.9496 - loss: 0.2258 - precision: 0.9616 - recall: 0.9407 - val_AUC: 0.9848 - val_accuracy: 0.9493 - val_loss: 0.2285 - val_precision: 0.9618 - val_recall: 0.9353
Epoch 34/130
2378/2382 ━━━━━━━━━━━━━━━━━━━━ 1s 268ms/step - AUC: 0.9878 - accuracy: 0.9515 - loss: 0.2222 - precision: 0.9620 - recall: 0.9439

2025-12-03 21:50:46.965517: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 268ms/step - AUC: 0.9878 - accuracy: 0.9515 - loss: 0.2222 - precision: 0.9620 - recall: 0.9439

2025-12-03 21:51:07.275241: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 665s 279ms/step - AUC: 0.9874 - accuracy: 0.9505 - loss: 0.2243 - precision: 0.9603 - recall: 0.9438 - val_AUC: 0.9849 - val_accuracy: 0.9479 - val_loss: 0.2283 - val_precision: 0.9581 - val_recall: 0.9363
Epoch 35/130
2377/2382 ━━━━━━━━━━━━━━━━━━━━ 1s 269ms/step - AUC: 0.9867 - accuracy: 0.9498 - loss: 0.2258 - precision: 0.9612 - recall: 0.9416

2025-12-03 22:01:53.997605: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 269ms/step - AUC: 0.9867 - accuracy: 0.9498 - loss: 0.2258 - precision: 0.9612 - recall: 0.9416

2025-12-03 22:02:14.808361: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 664s 278ms/step - AUC: 0.9871 - accuracy: 0.9511 - loss: 0.2239 - precision: 0.9622 - recall: 0.9433 - val_AUC: 0.9851 - val_accuracy: 0.9498 - val_loss: 0.2298 - val_precision: 0.9749 - val_recall: 0.9229
Epoch 36/130
2375/2382 ━━━━━━━━━━━━━━━━━━━━ 1s 269ms/step - AUC: 0.9884 - accuracy: 0.9548 - loss: 0.2183 - precision: 0.9635 - recall: 0.9489

2025-12-03 22:12:57.880713: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 269ms/step - AUC: 0.9884 - accuracy: 0.9548 - loss: 0.2183 - precision: 0.9635 - recall: 0.9489

2025-12-03 22:13:18.526119: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 669s 281ms/step - AUC: 0.9881 - accuracy: 0.9538 - loss: 0.2197 - precision: 0.9624 - recall: 0.9483 - val_AUC: 0.9857 - val_accuracy: 0.9512 - val_loss: 0.2238 - val_precision: 0.9665 - val_recall: 0.9343
Epoch 37/130
2374/2382 ━━━━━━━━━━━━━━━━━━━━ 2s 268ms/step - AUC: 0.9878 - accuracy: 0.9527 - loss: 0.2203 - precision: 0.9625 - recall: 0.9456

2025-12-03 22:24:04.205949: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 268ms/step - AUC: 0.9878 - accuracy: 0.9527 - loss: 0.2203 - precision: 0.9625 - recall: 0.9456

2025-12-03 22:24:06.890226: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size
2025-12-03 22:24:06.890401: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 661s 278ms/step - AUC: 0.9881 - accuracy: 0.9517 - loss: 0.2202 - precision: 0.9620 - recall: 0.9445 - val_AUC: 0.9853 - val_accuracy: 0.9517 - val_loss: 0.2249 - val_precision: 0.9693 - val_recall: 0.9324
Epoch 38/130
2373/2382 ━━━━━━━━━━━━━━━━━━━━ 2s 269ms/step - AUC: 0.9872 - accuracy: 0.9514 - loss: 0.2220 - precision: 0.9620 - recall: 0.9437

2025-12-03 22:35:07.504419: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 269ms/step - AUC: 0.9873 - accuracy: 0.9514 - loss: 0.2220 - precision: 0.9620 - recall: 0.9437

2025-12-03 22:35:29.083230: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 664s 279ms/step - AUC: 0.9881 - accuracy: 0.9533 - loss: 0.2200 - precision: 0.9624 - recall: 0.9474 - val_AUC: 0.9855 - val_accuracy: 0.9512 - val_loss: 0.2257 - val_precision: 0.9693 - val_recall: 0.9315
Epoch 39/130
2372/2382 ━━━━━━━━━━━━━━━━━━━━ 2s 269ms/step - AUC: 0.9887 - accuracy: 0.9535 - loss: 0.2172 - precision: 0.9636 - recall: 0.9465

2025-12-03 22:46:12.092360: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 269ms/step - AUC: 0.9887 - accuracy: 0.9535 - loss: 0.2172 - precision: 0.9636 - recall: 0.9465

2025-12-03 22:46:33.878513: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 669s 281ms/step - AUC: 0.9888 - accuracy: 0.9527 - loss: 0.2177 - precision: 0.9615 - recall: 0.9471 - val_AUC: 0.9860 - val_accuracy: 0.9508 - val_loss: 0.2227 - val_precision: 0.9647 - val_recall: 0.9353
Epoch 40/130
2371/2382 ━━━━━━━━━━━━━━━━━━━━ 2s 268ms/step - AUC: 0.9891 - accuracy: 0.9571 - loss: 0.2146 - precision: 0.9655 - recall: 0.9508

2025-12-03 22:57:18.750521: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 268ms/step - AUC: 0.9891 - accuracy: 0.9571 - loss: 0.2146 - precision: 0.9655 - recall: 0.9508

2025-12-03 22:57:22.358274: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size
2025-12-03 22:57:22.363277: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 662s 278ms/step - AUC: 0.9892 - accuracy: 0.9559 - loss: 0.2155 - precision: 0.9647 - recall: 0.9501 - val_AUC: 0.9861 - val_accuracy: 0.9498 - val_loss: 0.2234 - val_precision: 0.9592 - val_recall: 0.9391
Epoch 41/130
2371/2382 ━━━━━━━━━━━━━━━━━━━━ 2s 270ms/step - AUC: 0.9885 - accuracy: 0.9546 - loss: 0.2180 - precision: 0.9639 - recall: 0.9479

2025-12-03 23:08:25.321911: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 270ms/step - AUC: 0.9885 - accuracy: 0.9546 - loss: 0.2180 - precision: 0.9639 - recall: 0.9479

2025-12-03 23:08:47.697336: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 667s 280ms/step - AUC: 0.9891 - accuracy: 0.9556 - loss: 0.2160 - precision: 0.9651 - recall: 0.9489 - val_AUC: 0.9862 - val_accuracy: 0.9503 - val_loss: 0.2229 - val_precision: 0.9610 - val_recall: 0.9382
Epoch 42/130
2369/2382 ━━━━━━━━━━━━━━━━━━━━ 3s 269ms/step - AUC: 0.9878 - accuracy: 0.9554 - loss: 0.2183 - precision: 0.9655 - recall: 0.9475

2025-12-03 23:19:28.524787: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 269ms/step - AUC: 0.9878 - accuracy: 0.9554 - loss: 0.2183 - precision: 0.9655 - recall: 0.9475

2025-12-03 23:19:51.247670: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 669s 281ms/step - AUC: 0.9882 - accuracy: 0.9557 - loss: 0.2171 - precision: 0.9652 - recall: 0.9491 - val_AUC: 0.9864 - val_accuracy: 0.9522 - val_loss: 0.2210 - val_precision: 0.9630 - val_recall: 0.9401
Epoch 43/130
2368/2382 ━━━━━━━━━━━━━━━━━━━━ 3s 267ms/step - AUC: 0.9892 - accuracy: 0.9572 - loss: 0.2139 - precision: 0.9671 - recall: 0.9502

2025-12-03 23:30:32.398328: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 267ms/step - AUC: 0.9892 - accuracy: 0.9572 - loss: 0.2139 - precision: 0.9671 - recall: 0.9502

2025-12-03 23:30:36.614593: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size
2025-12-03 23:30:36.614719: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 662s 278ms/step - AUC: 0.9893 - accuracy: 0.9560 - loss: 0.2147 - precision: 0.9655 - recall: 0.9496 - val_AUC: 0.9865 - val_accuracy: 0.9527 - val_loss: 0.2208 - val_precision: 0.9577 - val_recall: 0.9467
Epoch 44/130
2367/2382 ━━━━━━━━━━━━━━━━━━━━ 4s 268ms/step - AUC: 0.9904 - accuracy: 0.9573 - loss: 0.2109 - precision: 0.9658 - recall: 0.9513

2025-12-03 23:41:37.464483: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 268ms/step - AUC: 0.9904 - accuracy: 0.9573 - loss: 0.2109 - precision: 0.9658 - recall: 0.9513

2025-12-03 23:41:42.053417: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size
2025-12-03 23:41:42.053785: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 665s 279ms/step - AUC: 0.9899 - accuracy: 0.9571 - loss: 0.2124 - precision: 0.9670 - recall: 0.9502 - val_AUC: 0.9864 - val_accuracy: 0.9536 - val_loss: 0.2201 - val_precision: 0.9604 - val_recall: 0.9458
Epoch 45/130
2366/2382 ━━━━━━━━━━━━━━━━━━━━ 4s 268ms/step - AUC: 0.9905 - accuracy: 0.9573 - loss: 0.2104 - precision: 0.9644 - recall: 0.9522

2025-12-03 23:52:42.251477: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 268ms/step - AUC: 0.9905 - accuracy: 0.9573 - loss: 0.2104 - precision: 0.9644 - recall: 0.9522

2025-12-03 23:52:47.069658: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size
2025-12-03 23:52:47.069754: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 662s 278ms/step - AUC: 0.9896 - accuracy: 0.9551 - loss: 0.2141 - precision: 0.9633 - recall: 0.9499 - val_AUC: 0.9864 - val_accuracy: 0.9522 - val_loss: 0.2226 - val_precision: 0.9750 - val_recall: 0.9277
Epoch 46/130
2365/2382 ━━━━━━━━━━━━━━━━━━━━ 4s 268ms/step - AUC: 0.9892 - accuracy: 0.9546 - loss: 0.2140 - precision: 0.9629 - recall: 0.9496

2025-12-04 00:03:44.736912: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 269ms/step - AUC: 0.9892 - accuracy: 0.9546 - loss: 0.2140 - precision: 0.9629 - recall: 0.9496

2025-12-04 00:04:08.716356: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 663s 278ms/step - AUC: 0.9894 - accuracy: 0.9544 - loss: 0.2145 - precision: 0.9633 - recall: 0.9486 - val_AUC: 0.9864 - val_accuracy: 0.9541 - val_loss: 0.2204 - val_precision: 0.9742 - val_recall: 0.9324
Epoch 47/130
2364/2382 ━━━━━━━━━━━━━━━━━━━━ 4s 270ms/step - AUC: 0.9896 - accuracy: 0.9570 - loss: 0.2125 - precision: 0.9642 - recall: 0.9524

2025-12-04 00:14:52.466003: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 271ms/step - AUC: 0.9896 - accuracy: 0.9570 - loss: 0.2125 - precision: 0.9643 - recall: 0.9524

2025-12-04 00:15:16.747295: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 678s 285ms/step - AUC: 0.9893 - accuracy: 0.9575 - loss: 0.2130 - precision: 0.9670 - recall: 0.9509 - val_AUC: 0.9866 - val_accuracy: 0.9550 - val_loss: 0.2197 - val_precision: 0.9742 - val_recall: 0.9343
Epoch 48/130
2363/2382 ━━━━━━━━━━━━━━━━━━━━ 5s 270ms/step - AUC: 0.9902 - accuracy: 0.9569 - loss: 0.2107 - precision: 0.9682 - recall: 0.9483

2025-12-04 00:26:08.952067: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 270ms/step - AUC: 0.9902 - accuracy: 0.9569 - loss: 0.2107 - precision: 0.9682 - recall: 0.9484

2025-12-04 00:26:14.574475: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size
2025-12-04 00:26:14.574771: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 666s 279ms/step - AUC: 0.9900 - accuracy: 0.9573 - loss: 0.2110 - precision: 0.9662 - recall: 0.9512 - val_AUC: 0.9863 - val_accuracy: 0.9512 - val_loss: 0.2258 - val_precision: 0.9778 - val_recall: 0.9229
Epoch 49/130
2362/2382 ━━━━━━━━━━━━━━━━━━━━ 5s 270ms/step - AUC: 0.9899 - accuracy: 0.9568 - loss: 0.2110 - precision: 0.9661 - recall: 0.9501

2025-12-04 00:37:16.089490: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 270ms/step - AUC: 0.9899 - accuracy: 0.9568 - loss: 0.2110 - precision: 0.9662 - recall: 0.9501

2025-12-04 00:37:40.635386: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 671s 282ms/step - AUC: 0.9902 - accuracy: 0.9580 - loss: 0.2100 - precision: 0.9665 - recall: 0.9523 - val_AUC: 0.9865 - val_accuracy: 0.9545 - val_loss: 0.2192 - val_precision: 0.9704 - val_recall: 0.9372
Epoch 50/130
2361/2382 ━━━━━━━━━━━━━━━━━━━━ 5s 269ms/step - AUC: 0.9912 - accuracy: 0.9596 - loss: 0.2065 - precision: 0.9681 - recall: 0.9539

2025-12-04 00:48:24.839067: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 270ms/step - AUC: 0.9911 - accuracy: 0.9596 - loss: 0.2066 - precision: 0.9681 - recall: 0.9538

2025-12-04 00:48:31.169085: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size
2025-12-04 00:48:31.169254: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 670s 281ms/step - AUC: 0.9902 - accuracy: 0.9589 - loss: 0.2097 - precision: 0.9684 - recall: 0.9522 - val_AUC: 0.9865 - val_accuracy: 0.9560 - val_loss: 0.2189 - val_precision: 0.9733 - val_recall: 0.9372
Epoch 51/130
2360/2382 ━━━━━━━━━━━━━━━━━━━━ 5s 269ms/step - AUC: 0.9905 - accuracy: 0.9590 - loss: 0.2076 - precision: 0.9684 - recall: 0.9518

2025-12-04 00:59:32.929399: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 269ms/step - AUC: 0.9905 - accuracy: 0.9590 - loss: 0.2076 - precision: 0.9684 - recall: 0.9518

2025-12-04 00:59:39.362634: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size
2025-12-04 00:59:39.362803: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 664s 279ms/step - AUC: 0.9901 - accuracy: 0.9589 - loss: 0.2093 - precision: 0.9685 - recall: 0.9520 - val_AUC: 0.9868 - val_accuracy: 0.9527 - val_loss: 0.2195 - val_precision: 0.9731 - val_recall: 0.9305
Epoch 52/130
2359/2382 ━━━━━━━━━━━━━━━━━━━━ 6s 270ms/step - AUC: 0.9903 - accuracy: 0.9605 - loss: 0.2071 - precision: 0.9695 - recall: 0.9538

2025-12-04 01:10:38.762702: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 270ms/step - AUC: 0.9903 - accuracy: 0.9605 - loss: 0.2071 - precision: 0.9695 - recall: 0.9539

2025-12-04 01:11:04.378091: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 666s 280ms/step - AUC: 0.9908 - accuracy: 0.9601 - loss: 0.2070 - precision: 0.9688 - recall: 0.9541 - val_AUC: 0.9867 - val_accuracy: 0.9536 - val_loss: 0.2212 - val_precision: 0.9770 - val_recall: 0.9286
Epoch 53/130
2358/2382 ━━━━━━━━━━━━━━━━━━━━ 6s 268ms/step - AUC: 0.9909 - accuracy: 0.9598 - loss: 0.2066 - precision: 0.9673 - recall: 0.9547

2025-12-04 01:21:41.205784: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 268ms/step - AUC: 0.9909 - accuracy: 0.9598 - loss: 0.2066 - precision: 0.9673 - recall: 0.9547

2025-12-04 01:22:06.717509: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 667s 280ms/step - AUC: 0.9909 - accuracy: 0.9600 - loss: 0.2067 - precision: 0.9686 - recall: 0.9541 - val_AUC: 0.9867 - val_accuracy: 0.9555 - val_loss: 0.2188 - val_precision: 0.9742 - val_recall: 0.9353
Epoch 54/130
2357/2382 ━━━━━━━━━━━━━━━━━━━━ 6s 269ms/step - AUC: 0.9900 - accuracy: 0.9611 - loss: 0.2088 - precision: 0.9693 - recall: 0.9552

2025-12-04 01:32:49.413060: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 269ms/step - AUC: 0.9900 - accuracy: 0.9611 - loss: 0.2088 - precision: 0.9693 - recall: 0.9552

2025-12-04 01:32:56.832619: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size
2025-12-04 01:32:56.832723: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 668s 280ms/step - AUC: 0.9905 - accuracy: 0.9597 - loss: 0.2081 - precision: 0.9679 - recall: 0.9544 - val_AUC: 0.9871 - val_accuracy: 0.9560 - val_loss: 0.2173 - val_precision: 0.9724 - val_recall: 0.9382
Epoch 55/130
2356/2382 ━━━━━━━━━━━━━━━━━━━━ 6s 269ms/step - AUC: 0.9917 - accuracy: 0.9615 - loss: 0.2035 - precision: 0.9706 - recall: 0.9542

2025-12-04 01:43:56.332399: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 269ms/step - AUC: 0.9917 - accuracy: 0.9615 - loss: 0.2035 - precision: 0.9706 - recall: 0.9542

2025-12-04 01:44:03.904930: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size
2025-12-04 01:44:03.905085: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 667s 280ms/step - AUC: 0.9910 - accuracy: 0.9595 - loss: 0.2067 - precision: 0.9686 - recall: 0.9530 - val_AUC: 0.9872 - val_accuracy: 0.9574 - val_loss: 0.2158 - val_precision: 0.9706 - val_recall: 0.9429
Epoch 56/130
2355/2382 ━━━━━━━━━━━━━━━━━━━━ 7s 270ms/step - AUC: 0.9905 - accuracy: 0.9630 - loss: 0.2055 - precision: 0.9722 - recall: 0.9559

2025-12-04 01:55:05.936936: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 667s 280ms/step - AUC: 0.9908 - accuracy: 0.9621 - loss: 0.2048 - precision: 0.9716 - recall: 0.9551 - val_AUC: 0.9872 - val_accuracy: 0.9550 - val_loss: 0.2183 - val_precision: 0.9751 - val_recall: 0.9334
Epoch 57/130
2354/2382 ━━━━━━━━━━━━━━━━━━━━ 7s 270ms/step - AUC: 0.9915 - accuracy: 0.9622 - loss: 0.2044 - precision: 0.9712 - recall: 0.9554

2025-12-04 02:06:12.652364: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 270ms/step - AUC: 0.9915 - accuracy: 0.9622 - loss: 0.2045 - precision: 0.9712 - recall: 0.9554

2025-12-04 02:06:20.586091: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size
2025-12-04 02:06:20.586272: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 667s 280ms/step - AUC: 0.9912 - accuracy: 0.9615 - loss: 0.2053 - precision: 0.9705 - recall: 0.9553 - val_AUC: 0.9872 - val_accuracy: 0.9569 - val_loss: 0.2163 - val_precision: 0.9706 - val_recall: 0.9420
Epoch 58/130
2353/2382 ━━━━━━━━━━━━━━━━━━━━ 7s 271ms/step - AUC: 0.9908 - accuracy: 0.9606 - loss: 0.2050 - precision: 0.9705 - recall: 0.9525

2025-12-04 02:17:20.612943: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 271ms/step - AUC: 0.9908 - accuracy: 0.9606 - loss: 0.2050 - precision: 0.9705 - recall: 0.9525

2025-12-04 02:17:47.494482: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 675s 283ms/step - AUC: 0.9910 - accuracy: 0.9609 - loss: 0.2050 - precision: 0.9713 - recall: 0.9530 - val_AUC: 0.9871 - val_accuracy: 0.9550 - val_loss: 0.2146 - val_precision: 0.9641 - val_recall: 0.9448
Epoch 59/130
2352/2382 ━━━━━━━━━━━━━━━━━━━━ 8s 270ms/step - AUC: 0.9904 - accuracy: 0.9601 - loss: 0.2070 - precision: 0.9685 - recall: 0.9543

2025-12-04 02:28:32.720291: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 270ms/step - AUC: 0.9904 - accuracy: 0.9602 - loss: 0.2070 - precision: 0.9685 - recall: 0.9544

2025-12-04 02:28:51.205169: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size
2025-12-04 02:28:51.205422: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 676s 284ms/step - AUC: 0.9909 - accuracy: 0.9616 - loss: 0.2049 - precision: 0.9697 - recall: 0.9562 - val_AUC: 0.9872 - val_accuracy: 0.9564 - val_loss: 0.2169 - val_precision: 0.9743 - val_recall: 0.9372
Epoch 60/130
2351/2382 ━━━━━━━━━━━━━━━━━━━━ 8s 269ms/step - AUC: 0.9910 - accuracy: 0.9623 - loss: 0.2039 - precision: 0.9712 - recall: 0.9556

2025-12-04 02:39:47.108306: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 269ms/step - AUC: 0.9909 - accuracy: 0.9623 - loss: 0.2040 - precision: 0.9712 - recall: 0.9556

2025-12-04 02:39:56.093344: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size
2025-12-04 02:39:56.093434: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 664s 279ms/step - AUC: 0.9908 - accuracy: 0.9606 - loss: 0.2056 - precision: 0.9696 - recall: 0.9544 - val_AUC: 0.9870 - val_accuracy: 0.9536 - val_loss: 0.2242 - val_precision: 0.9799 - val_recall: 0.9258
Epoch 61/130
2350/2382 ━━━━━━━━━━━━━━━━━━━━ 8s 270ms/step - AUC: 0.9919 - accuracy: 0.9626 - loss: 0.2016 - precision: 0.9714 - recall: 0.9561

2025-12-04 02:50:53.204344: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 270ms/step - AUC: 0.9919 - accuracy: 0.9626 - loss: 0.2016 - precision: 0.9714 - recall: 0.9561

2025-12-04 02:51:21.163407: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 667s 280ms/step - AUC: 0.9913 - accuracy: 0.9620 - loss: 0.2037 - precision: 0.9710 - recall: 0.9555 - val_AUC: 0.9873 - val_accuracy: 0.9564 - val_loss: 0.2165 - val_precision: 0.9724 - val_recall: 0.9391
Epoch 62/130
2349/2382 ━━━━━━━━━━━━━━━━━━━━ 8s 269ms/step - AUC: 0.9915 - accuracy: 0.9651 - loss: 0.2015 - precision: 0.9726 - recall: 0.9598

2025-12-04 03:01:58.002711: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 269ms/step - AUC: 0.9915 - accuracy: 0.9651 - loss: 0.2015 - precision: 0.9726 - recall: 0.9598

2025-12-04 03:02:26.286076: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 665s 279ms/step - AUC: 0.9915 - accuracy: 0.9649 - loss: 0.2017 - precision: 0.9725 - recall: 0.9598 - val_AUC: 0.9871 - val_accuracy: 0.9560 - val_loss: 0.2175 - val_precision: 0.9743 - val_recall: 0.9363
Epoch 63/130
2348/2382 ━━━━━━━━━━━━━━━━━━━━ 9s 270ms/step - AUC: 0.9906 - accuracy: 0.9623 - loss: 0.2041 - precision: 0.9711 - recall: 0.9560

2025-12-04 03:13:03.933353: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388640 bytes after encountering the first element of size 8388640 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 0s 270ms/step - AUC: 0.9906 - accuracy: 0.9623 - loss: 0.2041 - precision: 0.9710 - recall: 0.9560

2025-12-04 03:13:32.367067: W tensorflow/core/kernels/data/prefetch_autotuner.cc:55] Prefetch autotuner tried to allocate 8388864 bytes after encountering the first element of size 8388864 bytes.This already causes the autotune ram budget to be exceeded. To stay within the ram budget, either increase the ram budget or reduce element size


2382/2382 ━━━━━━━━━━━━━━━━━━━━ 666s 280ms/step - AUC: 0.9909 - accuracy: 0.9611 - loss: 0.2045 - precision: 0.9694 - recall: 0.9555 - val_AUC: 0.9872 - val_accuracy: 0.9541 - val_loss: 0.2201 - val_precision: 0.9760 - val_recall: 0.9305


---
## 7. Model Evaluation and Final Conclusion

This section provides a comprehensive synthesis of the **EfficientNetV2B3** model's performance across its multi-stage training curriculum. By analyzing the transition from frozen feature extraction to global fine-tuning, we justify the selection of the final checkpoint as a clinically robust tool for pulmonary diagnostic assistance.

---

### 7.1 Final Model Performance and Phase Summary

The multi-stage unfreezing strategy successfully navigated the high-dimensional weight space of the 4-channel input model. The progression shows a clear trend of increasing sensitivity (Recall) and discriminative power (AUC) as the backbone was progressively specialized.

#### Convergence Analysis by Phase

| Phase | Epoch Range | Key Training Goal | $\Delta$ Val Accuracy (Start $\to$ End) | $\Delta$ Val Loss (Start $\to$ End) | Final Phase AUC |
| :--- | :--- | :--- | :--- | :--- | :--- |
| **Warm-Up** | 1 $\to$ 10 | Classifier Head Adaptation | $+2.36\%$ | $-10.94\%$ | $0.9536$ |
| **Mid-Tune** | 11 $\to$ 30 | Deep Backbone Refinement | $+4.83\%$ | $-27.65\%$ | $0.9844$ |
| **Fine-Tune** | 31 $\to$ 63 | Global Parameter Co-optimization | $+0.43\%$ | $-4.01\%$ | $\mathbf{0.9872}$ |

---

### 7.2 Strategic Model Selection: Justifying the Global Fine-Tune

While the **Mid-Tune** phase achieved a remarkable leap in performance, the **Global Fine-Tune (Phase 3)** provided the necessary "surgical" refinements to maximize clinical utility.

#### Precision/Recall Trade-off Analysis
In medical AI, a high **Recall** is often prioritized to ensure that potential pathologies are not missed (minimizing False Negatives).

* **Mid-Tune Peak (Epoch 30):** Val Recall: **0.9258** | Val Precision: **0.9662**
* **Fine-Tune Peak (Epoch 58):** Val Recall: **0.9448** | Val Precision: **0.9641**



**Rationale for Final Selection:**
The model from **Epoch 58** was selected as the final production weights (`final_efficientnet_path`). Although the Precision saw a negligible dip, the **Recall increased by nearly 2%**. In a clinical workflow, this shift is vital; the model became significantly better at identifying positive cases of lung opacity or pneumonia that a more conservative (frozen) backbone might have overlooked.

---

### 7.3 Architectural Decisions and Final Conclusion

The success of this EfficientNetV2B3 implementation is attributed to three core strategic pillars:

1.  **4-Channel Structural Synergy:** By unfreezing the entire model in the final phase, the initial kernels were able to adapt to the **Mask-Guided channel**, effectively learning to treat the lung parenchyma as a region of high visual interest.
2.  **Stability via BN-Freezing:** Despite unfreezing the convolutional weights, keeping **BatchNormalization layers frozen** prevented the pre-trained ImageNet statistics from diverging, ensuring the loss curve remained smooth even with a global unfreeze.
3.  **Cosine Decay Precision:** The use of **Cosine Decay** allowed the model to settle into the deepest valleys of the loss landscape, as evidenced by the steady improvement in AUC from $0.9844$ to $0.9872$ in the final stages.

#### Final Conclusion

The fine-tuned **EfficientNetV2B3** model is validated as a high-performance diagnostic aid. With a final **Validation AUC of 0.987** and a **Recall of 94.5%**, the model demonstrates an exceptional ability to generalize across complex pulmonary patterns while maintaining high specificity. This justifies its deployment as a reliable first-line tool for medical image analysis.

---

### 📄 References

* **Model Foundations:**
    * [EfficientNetV2 Keras Documentation](https://keras.io/api/applications/efficientnet_v2/)
    * [EfficientNetV2B3 Tensorflow Documentation](https://www.tensorflow.org/api_docs/python/tf/keras/applications/EfficientNetV2B3)
* **Anatomical Guidance:**
    1.  **[Attention U-Net: Learning Where to Look for the Pancreas](https://arxiv.org/abs/1804.03999)** - Foundational paper explaining why "mask-like" attention is vital for medical imaging.
    2.  **[Deep Learning for Lung Cancer Prognosis, Using 3D CNNs and Mask-Guided Attention](https://www.nature.com/articles/s41598-019-42523-x)** - A study in *Nature* showing how masks guide classification performance in pulmonary diagnostics.
    3.  **[Mask-Guided Convolutional Neural Network for Breast Cancer Segmentation and Classification](https://ieeexplore.ieee.org/document/8759523)** - Demonstrates using masks as a constraint to improve classification accuracy.
    4.  **[Anatomy-Aware Deep Learning for Medical Image Analysis](https://arxiv.org/abs/2101.01140)** - A comprehensive review of how anatomical context improves model generalizability.
* **Optimization Logic:**
    * [SGDR: Stochastic Gradient Descent with Warm Restarts](https://arxiv.org/abs/1608.03983)

---

### Future Work

1.  **Multiclass Expansion:** Moving beyond binary classification to differentiate between COVID-19, Viral Pneumonia, and Bacterial infections.
2.  **Develop:** Develop this models as Web application or Mobile app.