"""Builders for versioned Kafka prediction events."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any


def build_prediction_event(
    *,
    request_id: str,
    input_type: str,
    response: dict[str, Any],
) -> dict[str, Any]:
    """Create the canonical prediction-completed event payload.

    Args:
        request_id: UUID generated by the API route.
        input_type: Source category such as ``path``, ``url``, ``base64``, or
            ``upload``.
        response: Prediction response emitted by the inference service.

    Returns:
        Versioned event envelope consumed by persistence, analytics, monitoring,
        doctor-review, and notification consumers.
    """
    # The event envelope is versioned independently from the API response so
    # consumers can evolve without guessing which payload shape they received.
    return {
        "event_type": "prediction.completed",
        "event_version": "1.0",
        "occurred_at": datetime.now(timezone.utc).isoformat(),
        "request_id": request_id,
        "input_type": input_type,
        "payload": response,
    }
